### ISSUE TITLE
Uncaught TypeError: uri.match is not a function

### ISSUE THREAD

**Issue by Samuel29** [atom/tree-view#1063]
[Enter steps to reproduce:]

1. launching Atom from terminal with: `atom <folder-name>` 
2. got the error below

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.217.0-1

### Stack Trace

Uncaught TypeError: uri.match is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/project.js:330

TypeError: uri.match is not a function
    at Project.module.exports.Project.resolvePath (/app.asar/src/project.js:330:29)
    at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:410:26)
    at TreeView.module.exports.TreeView.show (/packages/tree-view/lib/tree-view.coffee:198:20)
    at /packages/tree-view/lib/tree-view-package.js:12:58)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at TreeView.show (/packages/file-icons/lib/consumers/tree-view.js:206:17)
    at TreeView.disposables.set.UI.onProjectsAvailable (/packages/file-icons/lib/consumers/tree-view.js:21:10)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at UI.emit (/packages/file-icons/lib/ui.js:113:16)
    at UI.emitProjectsAvailable (/packages/file-icons/lib/ui.js:147:38)
    at UI.setProjects (/packages/file-icons/lib/ui.js:284:12)
    at disposables.add.atom.project.onDidChangePaths.to (/packages/file-icons/lib/ui.js:22:45)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/app.asar/src/project.js:288:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/app.asar/src/atom-environment.js:1178:26)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:229:18)
    at emitThree (events.js:121:20)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -0:15.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.17 
atom-ternjs 0.18.2 
auto-reveal-in-sidebar 0.8.0 
auto-update-packages 1.0.1 
autocomplete-ansible 0.1.11 
busy-signal 1.3.0 
compare-files 0.8.0 
copy-as-rtf 0.9.3 
editorconfig 2.2.2 
file-bookmark 1.0.3 
file-icons 2.1.2 
format-sql 0.3.0 
git-plus 7.3.3 
git-time-machine 1.5.9 
intentions 1.1.2 
language-ansible 0.2.1 
language-protobuf 0.7.1 
language-r 0.4.1 
language-scala 1.1.8 
linter 2.1.2 
linter-ansible-linting 1.2.3 
linter-eslint 8.1.4 
linter-python-pep8 0.2.0 
linter-sass-lint 1.7.4 
linter-ui-default 1.2.2 
merge-conflicts 1.4.4 
minimap 4.27.1 
open-recent 5.0.0 
php-twig 4.0.0 
pigments 0.39.1 
project-manager 3.3.4 
react 0.16.2 
Remote-FTP 0.10.7 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.4 
tablr 1.8.3 
wordcount 2.10.4 
```

**Comment by Samuel29** [comment]
update: no matter how you open Atom (from macos' dock, terminal...) the same error happens.

**Comment by Ben3eeE** [comment]
Can you reproduce the issue in safe mode `atom --safe`?

**Comment by Ben3eeE** [comment]
It looks like you are running a dev version of the `tree-view` instead of the version that is bundled with Atom do this:

1. Exit Atom
1. Open a command prompt
1. execute apm uninstall tree-view

This will ensure that you run the version that is bundled with Atom. The latest dev version only works with Atom 1.17.
