### ISSUE TITLE
Uncaught TypeError: atom.workspace.toggle is not a function

### ISSUE THREAD

**Issue by Luchanso** [atom/tree-view#1064]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.217.0-1

### Stack Trace

Uncaught TypeError: atom.workspace.toggle is not a function

```
At /home/oluchansky/.atom/packages/tree-view/lib/tree-view.coffee:195

TypeError: atom.workspace.toggle is not a function
    at TreeView.module.exports.TreeView.toggle (/packages/tree-view/lib/tree-view.coffee:195:20)
    at /packages/tree-view/lib/tree-view-package.js:13:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:19.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
  2x -0:15.2.0 core:paste (atom-pane.pane.active)
     -0:14.1.0 tree-view:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-clock 0.1.6 
atom-ternjs 0.18.2 
busy-signal 1.3.0 
color-picker 2.2.5 
docblockr 0.9.4 
editorconfig 2.2.2 
file-icons 2.1.2 
git-blame 0.4.12 
git-control 0.9.0 
intentions 1.1.2 
javascript-snippets 1.2.1 
language-babel 2.57.2 
linter 2.1.2 
linter-eslint 8.1.4 
linter-ui-default 1.2.2 
minimap 4.27.1 
multi-cursor-increment 0.1.1 
node-debugger 1.10.1 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
script 3.14.1 
split-diff 1.3.0 
sync-settings 0.8.1 
Zen 0.16.4 
```

**Comment by Ben3eeE** [comment]
It looks like you are running a dev version of the `tree-view` instead of the version that is bundled with Atom do this:

1. Exit Atom
1. Open a command prompt
1. execute apm uninstall tree-view

This will ensure that you run the version that is bundled with Atom. The latest dev version only works with Atom 1.17.

Let me know if you have any questions.

**Comment by Luchanso** [comment]
yeah its fix my problem
