### ISSUE TITLE
Uncaught TypeError: atom.workspace.getCenter is not a function

### ISSUE THREAD

**Issue by eljenso** [atom/tree-view#1065]
[Enter steps to reproduce:]

Just upgraded a few packages (tree-view might be one of them). This error occurs when I try to show the tree-view.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.217.0-3

### Stack Trace

Uncaught TypeError: atom.workspace.getCenter is not a function

```
At /Users/jboettch/.atom/packages/tree-view/lib/tree-view.coffee:178

TypeError: atom.workspace.getCenter is not a function
    at TreeView.module.exports.TreeView.handleEvents (/packages/tree-view/lib/tree-view.coffee:178:37)
    at /packages/tree-view/lib/tree-view.coffee:48:6)
    at TreeViewPackage.getTreeViewInstance (/packages/tree-view/lib/tree-view-package.js:47:23)
    at /packages/tree-view/lib/tree-view-package.js:13:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:27.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.compact-tab-bar.no-tab-min-width.panel-contrast.compact-tree-view.blend-tree-view.theme-monokai.theme-atom-material-ui.has-custom-icons)
  2x -0:25.2.0 tree-view:toggle (atom-pane.pane.active)
     -0:02.3.0 tool-bar:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
angularjs 0.4.0 
atom-beautify 0.29.18 
atom-cg2-editor 0.0.2 
atom-jade 0.3.0 
atom-material-ui 1.3.9 
atom-typescript 11.0.1 
build-gulp 0.11.0 
busy-signal 1.3.0 
color-picker 2.2.5 
docblockr 0.9.4 
editorconfig 2.2.2 
ficus-syntax 2.0.0 
file-icons 2.1.2 
firewatch-syntax 1.1.1 
fonts 2.0.0 
geiger 2.1.0 
genesis-ui 0.5.0 
git-plus 7.3.3 
git-time-machine 1.5.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
increment-me 0.4.1 
intentions 1.1.2 
isotope-ui 2.8.0 
jumpy 3.1.3 
language-babel undefined 
language-cypher 0.3.0 
language-docker 1.1.7 
language-gradle 0.0.3 
language-haskell 1.12.1 
language-ini 1.19.0 
language-latex 1.0.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-pug 0.0.21 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.1.2 
linter-eslint 8.1.5 
linter-pug-lint 0.2.0 
linter-tslint 0.15.0 
linter-ui-default 1.2.2 
lipsum 0.1.0 
merge-conflicts 1.4.4 
minimap 4.27.1 
monokai 0.22.0 
pigments 0.39.1 
project-manager 3.3.4 
react 0.16.2 
release-notes 0.53.0 
run-command2 1.12.2 
sort-lines 0.14.0 
sync-settings 0.8.1 
tool-bar 1.1.0 
turbo-javascript 1.4.0 
```

**Comment by eljenso** [comment]
https://github.com/atom/tree-view/issues/991#issuecomment-292273617 fixed this for me.
