### ISSUE TITLE
Directory named __proto__ causes file tree to throw an error

### ISSUE THREAD

**Issue by Daniel15** [atom/tree-view#1079]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you open a project containing a directory named `__proto__`, the file tree throws several errors:

```
TypeError: entry.destroy is not a function
    at Directory.module.exports.Directory.reload (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tree-view\lib\directory.js:354:15)
    at Directory.module.exports.Directory.expand (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tree-view\lib\directory.js:383:12)
    at DirectoryView.module.exports.DirectoryView.expand (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tree-view\lib\directory-view.js:185:24)
    at new DirectoryView (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tree-view\lib\directory-view.js:77:14)
    at TreeView.<anonymous> (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:604:18)
    at TreeView.module.exports.TreeView.updateRoots (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:609:10)
    at new TreeView (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:82:12)
    at Object.createView (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tree-view\lib\main.js:118:25)
    at Object.activate (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tree-view\lib\main.js:24:14)
    at Package.module.exports.Package.activateNow (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:218:19)
    at C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:96:15)
    at C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\atom-environment.js:826:28
```

```
Uncaught TypeError: packagePath.indexOf is not a function
module.exports.NotificationIssue.getPackageName	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\notifications\lib\not…:221
module.exports.NotificationIssue.getRepoUrl	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\notifications\lib\not…:169
NotificationElement.renderFatalError	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\notifications\lib\not…:169
NotificationElement.render	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\notifications\lib\not…:161
NotificationElement.initialize	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\notifications\lib\not…:52
(anonymous function)	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\notifications\lib\mai…:89
module.exports.ViewRegistry.createView	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\view-registry.js:117
module.exports.ViewRegistry.getView	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\view-registry.js:84
addNotificationView	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\notifications\lib\mai…:126
(anonymous function)	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\notifications\lib\mai…:27
module.exports.Emitter.simpleDispatch	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter…:25
module.exports.Emitter.emit	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter…:141
module.exports.NotificationManager.addNotification	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\notification-manager.js:54
module.exports.NotificationManager.addFatalError	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\notification-manager.js:45
(anonymous function)	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\notifications\lib\mai…:53
module.exports.Emitter.simpleDispatch	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter…:25
module.exports.Emitter.emit	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter…:141
(anonymous function)	@	C:\Users\Daniel\AppData\Local\atom\app-1.16.0\resources\app.asar\src\atom-environment.js:897
```

### Steps to Reproduce
1. Create a new empty directory
2. Open the directory as a project in Atom
3. Right-click the project and select "New Folder". Call the folder `__proto__`

**Expected behavior:** 
Nothing bad happens

**Actual behavior:**
Errors are thrown. Even after closing and reopening Atom, errors continue to be thrown and the file tree is completely unusable until you delete the directory.

**Reproduces how often:** 100%

### Versions
Windows 10.0.16176
```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

Shout out to @zertosh for discovering that the string `__proto__` broke stuff on Facebook as well, and suggesting that someone sees whether it breaks anything in Atom/Nuclide 😛

**Comment by zertosh** [comment]
😢

**Comment by Alhadis** [comment]
It goes haywire with files that're named `__proto__`, too.
