### ISSUE TITLE
Uncaught TypeError: e.target.closest is not a function

### ISSUE THREAD

**Issue by renzosunico** [atom/tree-view#1088]
[Enter steps to reproduce:]

1. Add project folder
2. Move the newly added folder around.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.215.1

### Stack Trace

Uncaught TypeError: e.target.closest is not a function

```
At C:\Users\jsunico\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:1457

TypeError: e.target.closest is not a function
    at TreeView.module.exports.TreeView.onDragStart (/app.asar/node_modules/tree-view/lib/tree-view.js:1457:28)
    at /app.asar/node_modules/tree-view/lib/tree-view.js:165:24)
```

### Commands

```
  4x -0:44 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -0:35.1.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
svg-preview 0.11.0 
```

**Comment by 50Wliu** [comment]
@renzosunico Could you maybe capture a gif of this issue?  I'm having trouble reproducing.

**Comment by c0fe** [comment]
I obtained this error when opening a directory in Atom's explorer tree.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: el.getAttribute is not a function

```
At C:\Users\User\AppData\Local\atom\app-1.17.0\resources\app\src\workspace-element.js:283

TypeError: el.getAttribute is not a function
    at isTab (~/AppData/Local/atom/app-1.17.0/resources/app/src/workspace-element.js:283:12)
    at atom-workspace.handleDragStart (~/AppData/Local/atom/app-1.17.0/resources/app/src/workspace-element.js:141:10)
```

### Commands

```
     -1:12.6.0 tabs:close-all-tabs (div.title)
```

### Non-Core Packages

```

```

**Comment by atillaman** [comment]
well _on me_ this error happened when i tried to **merge my repository with the git tab.**
