### ISSUE TITLE
Uncaught TypeError: ref.is is not a function

### ISSUE THREAD

**Issue by jatubio** [atom/tree-view#1092]
[Enter steps to reproduce:]
1.Type Command+\ to hide the file tree view
 or
2.Using the top menu 'View'->'Toggle Tree View' gives the same error.

Atom: 1.16.0 x64
Windows 2008 SR.2
Thrown From: tree-view 0.215.1

**Stack Trace**

# Uncaught TypeError: _ref.is is not a function

```
TypeError: ref.is is not a function
    at atom-workspace.<anonymous> (file:///C:/XXX/.atom/packages/tree-view-open-files/lib/tree-view-open-files.coffee:22:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\XXX\Atom\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\XXX\Atom\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\XXX\Atom\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\XXX\Atom\resources\app.asar\src\atom-environment.js:1179:28)
    at EventEmitter.outerCallback (C:\XXX\Atom\resources\app.asar\src\application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

I'm not sure about what package is throwing the error. Because when i click to open one issue, the referenced package is: `https://atom.io/packages/tree-view-open-files`

**Comment by jatubio** [comment]
Perdón, no me dí cuenta de que tenía instalado otro paquete.

**Comment by uwyang** [comment]
Can you tell me what the fix is? 
I'm seeing the same error and I'm at lost.

**Comment by jatubio** [comment]
My problem was with another package, and i removed them.

Try to disable some packages and see if error dissapear
