### ISSUE TITLE
Uncaught Error: Replacing non-existent child

### ISSUE THREAD

**Issue by garrottkai** [atom/tree-view#1096]
Steps that caused problem
1. Opened one file from project in a window
2. Attempted to open another file from the project tree via split:right

Note: This same error occurs when multiple files are already open in tabs and then I attempt to split:right on one of them.

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.217.0-7

### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:142

Error: Replacing non-existent child
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:142:1)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:948:1)
    at TreeView.module.exports.TreeView.openSelectedEntrySplit (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:835:1)
    at TreeView.module.exports.TreeView.openSelectedEntryRight (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:844:1)
    at HTMLDivElement.atom.commands.add.tree-view:open-selected-entry-right (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:314:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1292:1)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:28.8.0 application:open (input.hidden-input)
     -0:09.2.0 tree-view:open-selected-entry-right (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-typescript 11.0.3 
busy-signal 1.4.1 
git-plus 7.8.0 
intentions 1.1.2 
linter 2.1.4 
linter-php 1.3.2 
linter-ui-default 1.4.0 
merge-conflicts 1.4.5 
Remote-FTP 0.10.7 
rest-client 1.3.1 
```

**Comment by rsese** [comment]
Can you reproduce in safe mode (`atom --safe`)?

**Comment by garrottkai** [comment]
Yes. Error is the same.

**Comment by rsese** [comment]
Thanks for confirming - I updated to 1.17.0 on macOS 10.12.4 and tried this:

1. `atom --safe`
2. Added a project with <kbd>cmd-shift-o</kbd>
3. Double clicked on a project file from the tree-view to open it.
4. Right-clicked on a different file from the tree-view and chose `Split Right`

But couldn't reproduce the error - can you confirm if these steps reproduce the error for you?

**Comment by garrottkai** [comment]
I followed these steps and ran into the same error.

**Comment by DanPurdy** [comment]
Hi there, having the exact same issue with atom-beta 1.19.0-beta2 I've included the console error too if that helps

<img width="552" alt="screen shot 2017-07-24 at 10 25 15" src="https://user-images.githubusercontent.com/1386054/28517970-3905b9e6-705e-11e7-873a-b12c8e6c893b.png">

I only started running into the error today and have been successfully opening split panes previously. 

I believe that moving from fullscreen on OSX to non fullscreen may be playing some part of it in my case as that is all I'd done this morning that was different.

Reloading atom meant that the problem persisted (ctrl +alt + cmd + L) but closing fully and reopening seemed to solve the problem. As the panes are now being split correctly again.

**Comment by JaapWijnen** [comment]
I'm getting the error on Atom version 1.19.7

[Enter steps to reproduce:]

1. Open up atom
2. Open a file
3. Right click another file and try to split right

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.217.2


### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145

Error: Replacing non-existent child
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145:47)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:984:27)
    at TreeView.module.exports.TreeView.openSelectedEntrySplit (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:835:30)
    at TreeView.module.exports.TreeView.openSelectedEntryRight (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:844:25)
    at HTMLDivElement.atom.commands.add.tree-view:open-selected-entry-right (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:314:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:23.3.0 application:reopen-project (input.hidden-input)
  2x -0:23.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:17.1.0 tree-view:add-file (span.name.icon.tex-icon.medium-blue)
     -0:13.5.0 tree-view:open-selected-entry-right (span.name.icon.tex-icon.medium-blue)
```

### Non-Core Packages

```
file-icons 2.1.11 
language-latex 1.1.1 
latex 0.46.0 
latex-completions 0.3.3 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
pdf-view 0.59.0 
pigments 0.40.2 
tree-view-git-status 1.4.0 
```
