### ISSUE TITLE
Uncaught TypeError: e.target.matches is not a function

### ISSUE THREAD

**Issue by c0fe** [atom/tree-view#1106]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.217.0-7

### Stack Trace

Uncaught TypeError: e.target.matches is not a function

```
At C:\Users\User\AppData\Local\atom\app-1.17.0\resources\app\node_modules\tree-view\lib\root-drag-and-drop.js:107

TypeError: e.target.matches is not a function
    at RootDragAndDropHandler.module.exports.RootDragAndDropHandler.onDragEnd (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/tree-view/lib/root-drag-and-drop.js:107:1)
    at RootDragAndDropHandler.onDragEnd (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/tree-view/lib/root-drag-and-drop.js:3:1)
```

### Commands

```
     -2:16.3.0 tabs:close-all-tabs (div.title)
```

### Non-Core Packages

```

```

**Comment by c0fe** [comment]
This error was produced by dragging items in the tree explorer on the left hand side in Atom.

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible?  And if so, can you also reproduce in safe mode (atom --safe)?

**Comment by RedstoneMedal** [comment]
I can reproduce in regular mode. This only occurs when you drag multiple files. I cannot reproduce this in safe mode.  
Atom version: 1.17.2
OS: Mac OS X 10.11.6

**Comment by rsese** [comment]
Thanks @RedstoneMedal - since it's not reproducible in safe mode, then it's likely that a community package is causing the problem.  You can disable them all and then enable one-by-one until you find the package where you can reproduce.

**Comment by c0fe** [comment]
I had no additional packages installed on mine though.

**Comment by rsese** [comment]
> I had no additional packages installed on mine though.

Yeah since you don't see the issue in safe mode, they might be 2 different causes for the same problem (but yours doesn't involve a community package).

Just to double check about my questions [above](https://github.com/atom/tree-view/issues/1106#issuecomment-304396345), it sounds like you've tried in safe mode already but can you also confirm if the error is reproducible?  If so, can you share a GIF of how you reproduce?

**Comment by c0fe** [comment]
@rsese I can try but the thing is that this error seems to come in and go without any reliable way to reproduce it. For example, if I have Atom open one file and I use Explorer (Windows) to open another file, the file may or may not open in a new window for some reason. If it does open in a new window, then this error would be reproducible them.

**Comment by rsese** [comment]
> I can try but the thing is that this error seems to come in and go without any reliable way to reproduce it.

ahhh gotcha :+1:  We can leave this open for a bit till someone can reproduce - about this part:

> This error was produced by dragging items in the tree explorer on the left hand side in Atom.

Can you clarify about how many items has caused the error and where you're dragging them to?

**Comment by c0fe** [comment]
`Can you clarify about how many items has caused the error and where you're dragging them to?`

I meant if you hover your mouse over files that show up in the tree and accidentally click and slightly drag a file it gives that error.

**Comment by heisian** [comment]
I was dragging a single file from a sub-folder into its parent folder and got the same issue.

Packages installed:
dockblockr
intentions
linter
linter-eslint
linter-ui-default
split-diff

That's it.. 

OS X 10.12.5
Atom 1.18.0
