### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by wsfuller** [atom/tree-view#1159]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.217.2

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:251

TypeError: Cannot read property 'dispose' of undefined
    at PaneAxis.module.exports.PaneAxis.unsubscribeFromChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:251:32)
    at PaneAxis.module.exports.PaneAxis.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:203:18)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:984:27)
    at TreeView.module.exports.TreeView.openSelectedEntrySplit (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:835:30)
    at TreeView.module.exports.TreeView.openSelectedEntryUp (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:852:25)
    at HTMLDivElement.atom.commands.add.tree-view:open-selected-entry-up (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:324:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:17.2.0 editor:consolidate-selections (input.hidden-input)
     -2:17.2.0 core:cancel (input.hidden-input)
     -2:16.9.0 core:move-down (input.hidden-input)
 26x -2:16.6.0 core:move-right (input.hidden-input)
 14x -2:14.9.0 core:backspace (input.hidden-input)
  4x -2:11 core:move-right (input.hidden-input)
 12x -2:10.2.0 core:select-right (input.hidden-input)
     -2:06.9.0 core:move-right (input.hidden-input)
  2x -2:04.7.0 core:backspace (input.hidden-input)
     -2:03.2.0 core:move-right (input.hidden-input)
     -1:58.4.0 core:save (input.hidden-input)
     -1:47.2.0 tree-view:remove (div.tool-panel.tree-view)
     -0:54.5.0 editor:select-to-first-character-of-line (input.hidden-input)
  4x -0:54 core:backspace (input.hidden-input)
     -0:51.6.0 core:save (input.hidden-input)
     -0:11.7.0 tree-view:open-selected-entry-up (span.name.icon.jsx-icon.medium-blue)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-alignment 0.13.0 
atom-beautify 0.30.4 
atom-html-templates 0.1.3 
atom-jade 0.3.0 
atom-live-server 2.1.2 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
autocomplete-angular-material 0.4.0 
busy-signal 1.4.3 
file-icons 2.1.10 
highlight-selected 0.13.1 
intentions 1.1.5 
jshint 1.8.6 
json-converter 0.2.4 
language-babel 2.69.0 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-jshint 3.1.5 
linter-ruby 1.2.5 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-autohider 1.5.3 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
open-recent 5.0.0 
pigments 0.40.1 
platformio-ide-terminal 2.5.5 
prettier-atom 0.37.0 
pretty-json 1.6.4 
todo-show 1.11.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/1159#issuecomment-321684522. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
