### ISSUE TITLE
Uncaught TypeError: Cannot read property 'closest' of null

### ISSUE THREAD

**Issue by mrodalgaard** [atom/tree-view#1194]
This happened after I removed the file using the tree view command. The error is actually thrown from Atom Core, but it seems like the tree view package is responsible. The file is deleted correctly, but I'm guessing this happens when the package tries to select the next file.

### Reproduce

1. Open a project
2. Open a file from outside the project
3. Open command palette
4. Execute "Tree View: Remove"

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'closest' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1087

TypeError: Cannot read property 'closest' of null
    at atom.confirm.buttons.Move to Trash (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1087:57)
    at ApplicationDelegate.module.exports.ApplicationDelegate.confirm (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:229:55)
    at AtomEnvironment.module.exports.AtomEnvironment.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1020:45)
    at TreeView.module.exports.TreeView.removeSelectedEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1056:25)
    at HTMLElement.tree-view:remove (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view-package.js:23:66)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:324:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:35.9.0 command-palette:toggle (input.hidden-input)
     -2:35.1.0 core:backspace (input.hidden-input)
     -2:33.5.0 core:confirm (input.hidden-input)
     -2:33.5.0 tree-view:remove (input.hidden-input)
     -0:51.9.0 intentions:highlight (input.hidden-input)
     -0:51.7.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:51.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:51.2.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:50.8.0 core:save (input.hidden-input)
     -0:21 command-palette:toggle (input.hidden-input)
     -0:17.9.0 core:select-all (input.hidden-input)
     -0:16.7.0 core:confirm (input.hidden-input)
     -0:16.7.0 tree-view:remove (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.7 
atom-material-ui 2.0.6 
atom-terminal 0.8.0 
atom-ternjs 0.18.3 
browser-refresh 0.9.0 
busy-signal 1.4.3 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.13 
intentions 1.1.5 
language-apache 1.7.0 
language-asciidoc 1.11.0 
language-autotools 2.0.1 
language-cmake 0.3.0 
language-diff 0.7.0 
language-gradle 0.0.3 
language-htaccess 0.1.1 
language-ini 1.19.0 
language-log 1.9.0 
language-swift 0.5.0 
lcov-info 0.12.0 
linter 2.2.0 
linter-bootlint 1.1.0 
linter-clang 4.1.2 
linter-coffeelint 1.3.1 
linter-csslint 2.0.0 
linter-eslint 8.3.2 
linter-htmlhint 1.3.4 
linter-jshint 3.1.6 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-ui-default 1.6.10 
menu-manager 0.6.0 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-split-diff 0.3.7 
monokai 0.24.0 
native-ui 0.24.0 
open-in-sourcetree 0.1.8 
pigments 0.40.2 
project-manager 3.3.5 
seti-ui 1.9.0 
sort-lines 0.18.0 
split-diff 1.5.1 
tab-numbers 0.6.1 
theme-switcher 1.1.0 
todo-show 2.1.0 
tree-view-autoresize 2.2.0 
vim-mode 0.66.0 
zentabs 0.8.8 
```

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce on macOS 10.12.6 with Atom 1.23.0-dev-9a9537261.
