### ISSUE TITLE
Failed to activate the tree-view package (File-icons error)

### ISSUE THREAD

**Issue by yulimik** [atom/tree-view#1247]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.221.3

### Stack Trace

Failed to activate the tree-view package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at resolve (path.js:1146:7)
    at /packages/file-icons/lib/filesystem/directory.js:33:32)
    at IconDelegate.getFallbackClasses (/packages/file-icons/lib/service/icon-delegate.js:103:19)
    at IconDelegate.getClasses (/packages/file-icons/lib/service/icon-delegate.js:72:11)
    at IconNode.refresh (/packages/file-icons/lib/service/icon-node.js:66:39)
    at /packages/file-icons/lib/service/icon-node.js:45:8)
    at Function.forElement (/packages/file-icons/lib/service/icon-node.js:157:17)
    at /packages/file-icons/lib/service/icon-service.js:30:19)
    at IconServices.updateDirectoryIcon (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/get-icon-services.js:62:37)
    at DirectoryView.module.exports.DirectoryView.updateIcon (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/directory-view.js:87:38)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/directory-view.js:37:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at IconServices.setElementIcons (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/get-icon-services.js:49:26)
    at TreeViewPackage.consumeElementIcons (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view-package.js:58:29)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:405:79)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:233:20)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
```

### Commands

```
     -0:04.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.16 
atom-typescript 10.1.13 
atom-wx 0.1.1 
auto-encoding 0.6.2 
autocomplete-ionic-framework 0.2.2 
autocomplete-ionic2-framework 0.3.2 
file-icons 2.0.7 
language-babel 2.48.5 
language-javascript-jsx 0.3.7 
language-vue 0.21.0 
linter 1.11.18 
react-es6-snippets 0.3.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

As you mentioned, it appears that this is being caused by the [file-icons](https://github.com/file-icons/atom/) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by sjkdhdkzjhdjkqwhkdjashjkdsahkew** [comment]
I had the same problem. What I did is I updated the file icon package and then everything worked fine.
