### ISSUE TITLE
Failed to initialize the tree-view package

### ISSUE THREAD

**Issue by jimknight** [atom/tree-view#1264]
[Enter steps to reproduce:]

0. I was already having problems getting treeview to show at all. Stopped working for some reason.
1. File - Reopen Project
2. Chose an old project

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.223.0

### Stack Trace

Failed to initialize the tree-view package

```
At Cannot read property 'initialize' of null

TypeError: Cannot read property 'initialize' of null
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:185:42)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.initializeIfNeeded (/Applications/Atom.app/Contents/Resources/app/src/package.js:178:16)
    at Object.deserialize (/Applications/Atom.app/Contents/Resources/app/src/package.js:507:24)
    at DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app/src/deserializer-manager.js:74:33)
    at Function.deserialize (/Applications/Atom.app/Contents/Resources/app/src/pane.js:36:40)
    at DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app/src/deserializer-manager.js:74:33)
    at PaneContainer.deserialize (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:59:44)
    at Dock.deserialize (/Applications/Atom.app/Contents/Resources/app/src/dock.js:426:30)
    at Workspace.deserialize (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:384:38)
    at AtomEnvironment.deserialize (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1259:47)
    at <anonymous>
```

### Commands

```
     -0:18 application:reopen-project (input.hidden-input)
```

### Non-Core Packages

```
atom-elixir 0.2.3 
atom-elixir-formatter 1.0.3 
autocomplete-elixir 1.5.16 
elixir-block 1.0.1 
elixir-jump-around 0.3.1 
elixir-pry 1.0.0 
isotope-ui 2.8.5 
language-elixir 0.22.0 
native-ui 0.26.2 
phoenix-elixir-snippets 0.4.0 
railscasts 0.2.2 
save-session 0.15.7 
```

**Comment by jimknight** [comment]
I rebuilt my packages and it went away. Thanks!
