### ISSUE TITLE
file-icons does not work in Electron 9

### ISSUE THREAD

**Issue by aminya** [atom/tree-view#1371]
This might be related to the file-icons package

https://github.com/file-icons/atom/issues/843

**Atom**: 1.56.0-dev-ffaba34b3 x64
**Electron**: 9.3.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.46

### Stack Trace

Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions

```
At internal/fs/utils.js:364

TypeError: Cannot mix BigInt and other types, use explicit conversions
    at BigIntStats._checkModeProperty (internal/fs/utils.js:364:21)
    at BigIntStats.StatsBase.isDirectory (internal/fs/utils.js:287:15)
    at FileSystem.resolveType (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:110:28)
    at FileSystem.get (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:69:13)
    at Object.iconClassForPath (/packages/file-icons/lib/service/icon-service.js:101:29)
    at IconServices.updateFileIcon (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:966980)
    at FileView.updateIcon (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:3393321)
    at new FileView (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:3393131)
    at DirectoryView.createViewForEntry (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2777221)
    at ~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2776911
    at Function.simpleDispatch (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:1188253)
    at Emitter.emit (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:1189694)
    at Directory.reload (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2772971)
    at Directory.expand (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2773191)
    at DirectoryView.expand (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2777686)
    at DirectoryView.toggleExpansion (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2777473)
    at TreeView.entryClicked (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:979926)
    at HTMLDivElement.<anonymous> (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:974373)
```

**Comment by aminya** [comment]
This might be related to file-icons package

**Atom**: 1.56.0-dev-ffaba34b3 x64
**Electron**: 9.3.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.46


### Stack Trace

Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions

```
At internal/fs/utils.js:364

TypeError: Cannot mix BigInt and other types, use explicit conversions
    at BigIntStats._checkModeProperty (internal/fs/utils.js:364:21)
    at BigIntStats.StatsBase.isDirectory (internal/fs/utils.js:287:15)
    at FileSystem.resolveType (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:110:28)
    at FileSystem.get (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:69:13)
    at Object.iconClassForPath (/packages/file-icons/lib/service/icon-service.js:101:29)
    at IconServices.updateFileIcon (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:966980)
    at FileView.updateIcon (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:3393321)
    at new FileView (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:3393131)
    at DirectoryView.createViewForEntry (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2777221)
    at ~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2776911
    at Function.simpleDispatch (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:1188253)
    at Emitter.emit (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:11:1189694)
    at Directory.reload (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2772971)
    at Directory.expand (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2773191)
    at DirectoryView.expand (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2777686)
    at DirectoryView.toggleExpansion (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:2777473)
    at TreeView.entryClicked (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:979926)
    at HTMLDivElement.<anonymous> (~/Documents/GitHub/JavaScript/@atom-ide-community/atom/out/Atom Dev x64/resources/app/static/<embedded>:14:974373)
```

**Comment by aminya** [comment]
This is fixed in the new version
