### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentElement' of null

### ISSUE THREAD

**Issue by LoliC0d3** [atom/tree-view#1376]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: "Arch Linux"
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.228.2

### Stack Trace

Uncaught TypeError: Cannot read property 'parentElement' of null

```
At /usr/lib/atom/node_modules/tree-view/lib/tree-view.js:1671

TypeError: Cannot read property 'parentElement' of null
    at TreeView.module.exports.TreeView.selectContinuousEntries (/usr/lib/atom/node_modules/tree-view/lib/tree-view.js:1671:52)
    at TreeView.module.exports.TreeView.onMouseDown (/usr/lib/atom/node_modules/tree-view/lib/tree-view.js:1613:14)
    at HTMLDivElement.<anonymous> (/usr/lib/atom/node_modules/tree-view/lib/tree-view.js:349:24)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
Hydrogen 2.14.7 
minimap 4.39.9 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
