### ISSUE TITLE
[WINDOWS] Tree View not working

### ISSUE THREAD

**Issue by Stoyvo** [atom/tree-view#206]
Failed to activate package named 'tree-view' TypeError: Unable to watch path
      at TypeError (native)
      at HandleWatcher.start (c:\Atom\resources\app\node_modules\pathwatcher\lib\main.js:66:29)
      at new HandleWatcher (c:\Atom\resources\app\node_modules\pathwatcher\lib\main.js:30:12)
      at new PathWatcher (c:\Atom\resources\app\node_modules\pathwatcher\lib\main.js:120:30)
      at Object.exports.watch (c:\Atom\resources\app\node_modules\pathwatcher\lib\main.js:179:12)
      at Directory.module.exports.Directory.subscribeToNativeChangeEvents (c:\Atom\resources\app\node_modules\pathwatcher\lib\directory.js:219:109)
      at c:\Atom\resources\app\node_modules\pathwatcher\lib\directory.js:33:24
      at Directory.module.exports.Emitter.emit (c:\Atom\resources\app\node_modules\emissary\lib\emitter.js:118:15)
      at Directory.module.exports.Emitter.on (c:\Atom\resources\app\node_modules\emissary\lib\emitter.js:50:16)
      at Directory.module.exports.Directory.watch (c:\Atom\resources\app\node_modules\tree-view\lib\directory.js:163:49)
      at Directory.module.exports.Directory.expand (c:\Atom\resources\app\node_modules\tree-view\lib\directory.js:215:19)
      at DirectoryView.module.exports.DirectoryView.expand (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:151:24)
      at DirectoryView.module.exports.DirectoryView.initialize (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:76:21)
      at DirectoryView.View (c:\Atom\resources\app\node_modules\space-pen\lib\space-pen.js:137:25)
      at new DirectoryView (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:18:50)
      at DirectoryView.module.exports.DirectoryView.createViewForEntry (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:113:16)
      at c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:88:24
      at Directory.module.exports.Emitter.emit (c:\Atom\resources\app\node_modules\emissary\lib\emitter.js:118:15)
      at Directory.module.exports.Directory.reload (c:\Atom\resources\app\node_modules\tree-view\lib\directory.js:201:28)
      at Directory.module.exports.Directory.expand (c:\Atom\resources\app\node_modules\tree-view\lib\directory.js:214:12)
      at DirectoryView.module.exports.DirectoryView.expand (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:151:24)
      at DirectoryView.module.exports.DirectoryView.initialize (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:76:21)
      at DirectoryView.View (c:\Atom\resources\app\node_modules\space-pen\lib\space-pen.js:137:25)
      at new DirectoryView (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:18:50)
      at DirectoryView.module.exports.DirectoryView.createViewForEntry (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:113:16)
      at c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:88:24
      at Directory.module.exports.Emitter.emit (c:\Atom\resources\app\node_modules\emissary\lib\emitter.js:118:15)
      at Directory.module.exports.Directory.reload (c:\Atom\resources\app\node_modules\tree-view\lib\directory.js:201:28)
      at Directory.module.exports.Directory.expand (c:\Atom\resources\app\node_modules\tree-view\lib\directory.js:214:12)
      at DirectoryView.module.exports.DirectoryView.expand (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:151:24)
      at DirectoryView.module.exports.DirectoryView.initialize (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:76:21)
      at DirectoryView.View (c:\Atom\resources\app\node_modules\space-pen\lib\space-pen.js:137:25)
      at new DirectoryView (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:18:50)
      at DirectoryView.module.exports.DirectoryView.createViewForEntry (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:113:16)
      at c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:88:24
      at Directory.module.exports.Emitter.emit (c:\Atom\resources\app\node_modules\emissary\lib\emitter.js:118:15)
      at Directory.module.exports.Directory.reload (c:\Atom\resources\app\node_modules\tree-view\lib\directory.js:201:28)
      at Directory.module.exports.Directory.expand (c:\Atom\resources\app\node_modules\tree-view\lib\directory.js:214:12)
      at DirectoryView.module.exports.DirectoryView.expand (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:151:24)
      at DirectoryView.module.exports.DirectoryView.initialize (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:76:21)
      at DirectoryView.View (c:\Atom\resources\app\node_modules\space-pen\lib\space-pen.js:137:25)
      at new DirectoryView (c:\Atom\resources\app\node_modules\tree-view\lib\directory-view.js:18:50)
      at TreeView.module.exports.TreeView.updateRoot (c:\Atom\resources\app\node_modules\tree-view\lib\tree-view.js:438:21)
      at TreeView.module.exports.TreeView.initialize (c:\Atom\resources\app\node_modules\tree-view\lib\tree-view.js:254:12)
      at TreeView.View (c:\Atom\resources\app\node_modules\space-pen\lib\space-pen.js:137:25)
      at TreeView.ScrollView (c:\Atom\resources\app\src\scroll-view.js:12:47)
      at new TreeView (c:\Atom\resources\app\node_modules\tree-view\lib\tree-view.js:41:45)
      at Object.module.exports.createView (c:\Atom\resources\app\node_modules\tree-view\lib\tree.js:88:25)
      at Object.module.exports.activate (c:\Atom\resources\app\node_modules\tree-view\lib\tree.js:22:14)
      at Package.module.exports.Package.activateNow (c:\Atom\resources\app\src\package.js:163:27)
      at c:\Atom\resources\app\src\package.js:149:28
      at Package.module.exports.Package.measure (c:\Atom\resources\app\src\package.js:95:15)
      at Package.module.exports.Package.activate (c:\Atom\resources\app\src\package.js:143:14)
      at PackageManager.module.exports.PackageManager.activatePackage (c:\Atom\resources\app\src\package-manager.js:109:21)
      at c:\Atom\resources\app\src\package-manager.js:177:19
      at c:\Atom\resources\app\src\config.js:231:20
      at Config.module.exports.Emitter.emit (c:\Atom\resources\app\node_modules\emissary\lib\emitter.js:118:15)
      at Config.module.exports.Config.update (c:\Atom\resources\app\src\config.js:254:19)
      at Config.module.exports.Config.set (c:\Atom\resources\app\src\config.js:166:14)
      at Config.module.exports.Config.removeAtKeyPath (c:\Atom\resources\app\src\config.js:209:12)
      at Package.module.exports.Package.enable (c:\Atom\resources\app\src\package.js:80:26)
      at PackageManager.module.exports.PackageManager.enablePackage (c:\Atom\resources\app\src\package-manager.js:65:14)
      at HTMLButtonElement.<anonymous> (c:\Atom\resources\app\node_modules\settings-view\lib\installed-package-view.js:185:27)
      at HTMLButtonElement.jQuery.event.dispatch (c:\Atom\resources\app\node_modules\space-pen\vendor\jquery.js:4676:9)
      at HTMLButtonElement.elemData.handle (c:\Atom\resources\app\node_modules\space-pen\vendor\jquery.js:4360:46)

**Comment by kevinsawicki** [comment]
Closing in favor of https://github.com/atom/tree-view/issues/278 which has more details.
