### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/Users/my0.username'

### ISSUE THREAD

**Issue by blissd** [atom/tree-view#281]
Uncaught Error: EACCES, permission denied '/Users/my0.username'

**Atom Version**: 0.156.0
**System**: Mac OS X 10.9.5
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.136.0

### Steps To Reproduce

1. ... Have the tree-view open to display two directories, both of which contain a file called 'a'.
2. ...Drag and drop the file 'a' from one directory to another. I would expect an overwrite warning, but instead there is an "permission denied" error. I have full access to the source and destination directories and files. 

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:74

Error: EACCES, permission denied '/Users/david0.bliss'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:679:18)
  at sync (/Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:55:12)
  at sync (/Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:61:24)
  at sync (/Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:61:24)
  at Function.sync (/Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:61:24)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:227:14)
  at TreeView.module.exports.TreeView.pasteEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:855:32)
  at space-pen-div.atom.commands.add.tree-view:paste (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:250:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by 50Wliu** [comment]
Please update Atom to the latest version.
