### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/michaeljcalkins/Sites/serpprogress/config/default.js'

### ISSUE THREAD

**Issue by michaeljcalkins** [atom/tree-view#302]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.139.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/michaeljcalkins/Sites/serpprogress/config/default.js'

```
At fs.js:580

Error: ENOENT, no such file or directory '/Users/michaeljcalkins/Sites/serpprogress/config/default.js'
  at Error (native)
  at Object.fs.renameSync (fs.js:580:18)
  at Object.fsPlus.moveSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:221:17)
  at TreeView.module.exports.TreeView.pasteEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:859:32)
  at space-pen-div.atom.commands.add.tree-view:paste (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:250:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
  6x -1:37.3 core:undo (input.hidden-input)
  2x -1:33.8 core:redo (input.hidden-input)
     -1:32.3 core:undo (input.hidden-input)
     -1:30.9 core:move-down (input.hidden-input)
  3x -1:30.5 editor:select-to-end-of-word (input.hidden-input)
  2x -1:29.7 core:backspace (input.hidden-input)
  2x -1:29.5 core:save (input.hidden-input)
  3x -0:51.4 core:close (input.hidden-input)
  3x -0:37.9 core:move-left (input.hidden-input)
  8x -0:37.3 core:select-left (input.hidden-input)
     -0:04.6 core:move-right (input.hidden-input)
     -0:04.2 core:backspace (input.hidden-input)
     -0:03.9 core:confirm (input.hidden-input)
     -0:01.6 core:select-all (input.hidden-input)
     -0:01.4 core:copy (input.hidden-input)
     -0:00.0 tree-view:paste (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
color-picker, v1.2.6
editorconfig, v0.2.2
highlight-line, v0.9.2
jshint, v1.1.3
language-ejs, v0.1.0
minimap, v3.4.9
monokai, v0.9.0

# Dev
No dev packages
```

/cc @atom/core

![screen shot 2015-01-02 at 11 33 30 am](https://cloud.githubusercontent.com/assets/8272012/5598932/4636b0be-9273-11e4-8695-bb93a962ffb4.png)

**Comment by izuzak** [comment]
This seems to be a `cut` variant of https://github.com/atom/tree-view/issues/356 (which is based on copy/paste). Just to make things easier to track, lets have a single issue for this -- I'm closing this in favor of #356 since it has some repro steps. :v: Thanks for the report!
