### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by azizur** [atom/tree-view#303]
Unable to open files larger then 2MB

1. have a file that is more then 2MB in size
2. try to open it

**Atom Version**: 0.165.0
**System**: Mac OS X 10.8.5
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.139.0

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Applications/Atom.app/Contents/Resources/app/src/project.js:462

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:462:15)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:439:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:393:19)
  at Workspace.module.exports.Workspace.openUriInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:409:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
```

### Config

```
{
  "tree-view": {
    "hideVcsIgnoredFiles": true
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.2.2
autoclose-html, v0.13.0
color-picker, v1.2.6
compass, v0.7.5
composer, v0.3.1
editor-stats, v0.16.0
language-clojure, v0.9.0
linter-clojure, v0.0.4
visual-bell, v0.9.0
wordpress, v0.2.0
wordpress-api, v1.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment]
Closing in favor of https://github.com/atom/atom/issues/4421
