### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by gponsu** [atom/tree-view#305]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.13.0-43-generic
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.139.0

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /opt/atom/resources/app/src/project.js:462

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/opt/atom/resources/app/src/project.js:462:15)
  at Project.module.exports.Project.bufferForPath (/opt/atom/resources/app/src/project.js:439:63)
  at Project.module.exports.Project.open (/opt/atom/resources/app/src/project.js:393:19)
  at Workspace.module.exports.Workspace.openUriInPane (/opt/atom/resources/app/src/workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (/opt/atom/resources/app/src/workspace.js:409:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/home/vicente/.atom/packages/linter/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/home/vicente/.atom/packages/linter/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -0:46.3 project-ring:toggle (input.hidden-input)
     -0:44.7 core:confirm (input.hidden-input)
     -0:32.3 core:copy (input.hidden-input)
     -0:15.5 project-find:show (input.hidden-input)
     -0:12.9 core:move-up (input.hidden-input)
  6x -0:11.7 core:backspace (input.hidden-input)
     -0:07.9 core:confirm (input.hidden-input)
  3x -0:00.0 core:copy (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-haml, v0.14.0
linter, v0.9.0
linter-rubocop, v0.2.1
linter-scss-lint, v0.0.11
preview-tabs, v0.1.6
project-ring, v0.18.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by lee-dohm** [comment]
Closing in favor of atom/atom#4421
