### ISSUE TITLE
Uncaught Error: EPERM, operation not permitted '\\howb01\cshare\Inetpub\wwwroot\reh_applications\DailyRevenue\adovbs.inc'

### ISSUE THREAD

**Issue by llompartg** [atom/tree-view#333]
1. Dragged a network folder into atom
2. Ctrl + P to search for specific a file and it showed that atom was indexing the files.
3. Checked something on the browser and when I was back the error was there

**Atom Version**: 0.174.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.148.0

### Stack Trace

Uncaught Error: EPERM, operation not permitted '\\howb01\cshare\Inetpub\wwwroot\reh_applications\DailyRevenue\adovbs.inc'

```
At c:\Users\llompartg\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:504

Error: EPERM, operation not permitted '\\howb01\cshare\Inetpub\wwwroot\reh_applications\DailyRevenue\adovbs.inc'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (c:\Users\llompartg\AppData\Local\atom\app-0.174.0\resources\atom\common\lib\asar.js:422:20)
  at Project.module.exports.Project.open (c:\Users\llompartg\AppData\Local\atom\app-0.174.0\resources\app\src\project.js:287:31)
  at Workspace.module.exports.Workspace.openURIInPane (c:\Users\llompartg\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:492:31)
  at Workspace.module.exports.Workspace.open (c:\Users\llompartg\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:418:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (c:\Users\llompartg\AppData\Local\atom\app-0.174.0\resources\app\node_modules\tree-view\lib\tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (c:\Users\llompartg\AppData\Local\atom\app-0.174.0\resources\app\node_modules\tree-view\lib\tree-view.js:383:18)
  at tree-view-file.<anonymous> (c:\Users\llompartg\AppData\Local\atom\app-0.174.0\resources\app\node_modules\tree-view\lib\tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (c:\Users\llompartg\AppData\Local\atom\app-0.174.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4676:9)
  at space-pen-div.elemData.handle (c:\Users\llompartg\AppData\Local\atom\app-0.174.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4360:46)

```

### Commands

```
     -0:03.7 command-palette:toggle (atom-pane.pane.active)
     -0:00.3 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:00.3 core:cancel (atom-text-editor.editor.mini)
  2x -0:00.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jsformat"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-jasmine, v0.5.0
color-picker, v1.4.0
language-csharp, v0.3.0
linter, v0.10.0
linter-jshint, v0.1.0
pretty-json, v0.3.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
This will be fixed in the next Atom version.
