### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by Bolza** [atom/tree-view#335]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.166.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.145.0

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /usr/share/atom/resources/app/src/project.js:355

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app/src/project.js:355:15)
  at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app/src/project.js:332:63)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app/src/project.js:286:19)
  at Workspace.module.exports.Workspace.openUriInPane (/usr/share/atom/resources/app/src/workspace.js:485:29)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:412:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -0:41.0 application:open-file (atom-text-editor.editor)
     -0:36.8 application:open-folder (atom-text-editor.editor)
     -0:07.6 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:00.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:00.0 core:cancel (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v1.5.0
linter, v0.9.1
linter-jscs, v1.4.9

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Please update Atom to the latest version and see atom/atom#307 for the main issue.
