### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by DebGit** [atom/tree-view#338]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.148.0

### Stack Trace

Uncaught TypeError: Cannot read property 'top' of undefined

```
At /Users/DS/Softwares/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:958

TypeError: Cannot read property 'top' of undefined
  at TreeView.module.exports.TreeView.scrollToEntry (/Users/DS/Softwares/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:958:38)
  at TreeView.module.exports.TreeView.revealActiveFile (/Users/DS/Softwares/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:527:30)
  at atom-workspace.disposables.add.atom.commands.add.tree-view:reveal-active-file (/Users/DS/Softwares/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/main.js:55:39)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/DS/Softwares/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Users/DS/Softwares/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/DS/Softwares/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/Users/DS/Softwares/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/Users/DS/Softwares/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -35:08.9 mavensmate:open-project (atom-text-editor.editor)
     -34:57.3 mavensmate:edit-project (atom-text-editor.editor)
     -34:24.2 mavensmate:open-project (iframe.native-key-bindings)
     -34:03.0 mavensmate:new-project (iframe.native-key-bindings)
  2x -32:40.8 webkitTransitionEnd (div#modal-3c783ce0-a30e-11e4-8741-e5b9dc3266cb.modal.fade)
     -32:24.2 mavensmate:open-project (atom-pane.pane.active)
     -32:17.3 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
 18x -32:00.6 core:backspace (atom-text-editor.editor.mini)
     -31:34.8 tree-view:toggle-focus (atom-pane.pane.active)
     -31:17.0 dev-live-reload:reload-all (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  9x -30:47.0 webkitTransitionEnd (li.tab.sortable)
     -30:00.0 tree-view:reveal-active-file (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.14
color-picker, v1.4.4

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Can you please list some reproduction steps if possible?
Also, can you reproduce this in safe mode (`atom --safe`)?

**Comment by facundofarias** [comment]
It also happening to me all the time.
I will try with the safe mode.

**Comment by izuzak** [comment]
@facundofarias Any luck with reproducing this in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)? If you can still reproduce in safe mode, could you post the full details of the exception (stack trace, command history and config) + steps which reproduce the problem for you? :pray:

**Comment by facundofarias** [comment]
I did update Atom, and then I updated some dependencies that were showing some deprecation warnings, and the problem it's gone. Perhaps was due that? Not sure.

**Comment by izuzak** [comment]
@facundofarias Thanks for letting us know. Gonna close this for now and reopen is someone can reproduce in latest Atom. :+1:

**Comment by krainboltgreene** [comment]
Still getting this :/

**Comment by serapath** [comment]
me too. any progress?

**Comment by mnquintana** [comment]
@serapath @krainboltgreene What version of Atom?

**Comment by serapath** [comment]
**$>** `atom --version`

> 1.0.0

**Comment by mnquintana** [comment]
@serapath Can you reproduce this in safe mode? (`atom --safe`)

**Comment by serapath** [comment]
no

**Comment by mnquintana** [comment]
@serapath That means a community package you have installed or your [init script](https://atom.io/docs/latest/hacking-atom-the-init-file) is causing this, rather than tree-view.

**Comment by serapath** [comment]
how would i go about figuring out which it could be?
