### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by yokozawa** [atom/tree-view#353]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.9.5
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.149.0

### Stack Trace

Uncaught Error: Module did not self-register.

```
At /Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) [as .node] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/yokozawa/.atom/packages/tree-view/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/Users/yokozawa/.atom/packages/tree-view/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:140:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/yokozawa/.atom/packages/tree-view/lib/directory.coffee:5:15)
  at Object.<anonymous> (/Users/yokozawa/.atom/packages/tree-view/lib/directory.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:74:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/yokozawa/.atom/packages/tree-view/lib/tree-view.coffee:14:13)
  at Object.<anonymous> (/Users/yokozawa/.atom/packages/tree-view/lib/tree-view.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:74:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.module.exports.createView (/Users/yokozawa/.atom/packages/tree-view/lib/main.coffee:54:18)
  at atom-workspace.disposables.add.atom.commands.add.tree-view:toggle (/Users/yokozawa/.atom/packages/tree-view/lib/main.coffee:30:31)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -4:33.3 application:new-window (atom-text-editor.editor)
     -4:18.8 application:open (atom-text-editor.editor)
     -2:25.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -2:22.8 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -2:10.0 incompatible-packages:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:49.0 core:close (div.release-notes.padded.pane-item.native-key-bindings)
  2x -1:47.1 pane:show-next-item (div.deprecation-cop.pane-item.native-key-bindings)
     -1:45.9 core:close (atom-text-editor.editor)
  2x -1:45.3 pane:show-next-item (atom-text-editor.editor.is-focused)
     -1:44.4 pane:show-previous-item (div.tool-panel.panel-bottom.padded.incompatible-packages.native-key-bindings)
     -1:42.1 core:close (div.deprecation-cop.pane-item.native-key-bindings)
     -1:40.9 pane:show-next-item (atom-text-editor.editor.is-focused)
     -1:40.5 core:close (div.tool-panel.panel-bottom.padded.incompatible-packages.native-key-bindings)
     -1:39.2 settings-view:open (atom-text-editor.editor.is-focused)
     -0:01.1 tree-view:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  },
  "tree-view": {
    "hideVcsIgnoredFiles": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.2
atom-runner, v2.2.0
autocomplete-plus, v1.1.0
compare-files, v0.3.1
git-log, v0.2.0
html2haml, v0.6.0
japanese-wrap, v0.2.3
language-haml, v0.15.0
recent-files, v0.3.0
regex-railroad-diagram, v0.6.3
tree-view, v0.149.0
web-view, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
It looks like you have the tree-view installed to `/Users/yokozawa/.atom/packages/tree-view`.

The tree-view package is bundled with Atom and should not be explicitly installed.

If you delete the `/Users/yokozawa/.atom/packages/tree-view` directory and restart Atom, this error should go away.
