### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/home/nick/Development/hang/app/client/assets/fav/favicon.ico'

### ISSUE THREAD

**Issue by nickckaye** [atom/tree-view#354]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: linux 3.13.0-45-generic
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.148.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/home/nick/Development/hang/app/client/assets/fav/favicon.ico'

```
At fs.js:580

Error: ENOENT, no such file or directory '/home/nick/Development/hang/app/client/assets/fav/favicon.ico'
  at Error (native)
  at Object.fs.renameSync (fs.js:580:18)
  at Object.fsPlus.moveSync (/usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:221:17)
  at TreeView.module.exports.TreeView.pasteEntries (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:859:32)
  at space-pen-div.atom.commands.add.tree-view:paste (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:250:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
  4x -1:21.1 core:move-right (atom-text-editor.editor)
     -1:15.7 core:move-down (atom-text-editor.editor)
 13x -1:15.7 core:move-left (atom-text-editor.editor)
  5x -1:13.4 core:move-right (atom-text-editor.editor)
     -1:12.4 core:backspace (atom-text-editor.editor)
     -1:11.7 core:save (atom-text-editor.editor)
  3x -1:05.8 last-cursor-position:previous (div.image-view)
  5x -1:04.3 core:close (div.image-view)
     -0:42.8 tree-view:remove (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -0:34.5 tree-view:paste (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -0:27.4 core:confirm (atom-text-editor.editor.mini)
     -0:21.5 tree-view:paste (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -0:10.4 core:confirm (atom-text-editor.editor.mini)
     -0:09.2 tree-view:expand-directory (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -0:08.9 core:move-down (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -0:00.4 tree-view:paste (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "tree-view": {
    "showOnRightSide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
git-log, v0.2.0
last-cursor-position, v0.7.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by nickckaye** [comment]
Ubuntu 14.04 - In system file browser (nautilus) Copied an image file from `~/Desktop/` and Pasted into the tree view, in a folder that had recently had all its contents `git rm`'d.

**Comment by izuzak** [comment]
Seems to be the same problem as in https://github.com/atom/tree-view/issues/302 (stack traces are the same). Also, seems to be a `cut` variant of https://github.com/atom/tree-view/issues/356. Going to close this so that we have single tracking issue for this. Thanks for the report!
