### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/matrix/workspace/SAGN-NUE/app/controllers/achievement/unlocks_controller.rb'

### ISSUE THREAD

**Issue by TICC9180** [atom/tree-view#360]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.154.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/matrix/workspace/SAGN-NUE/app/controllers/achievement/unlocks_controller.rb'

```
At fs.js:639

Error: ENOENT, no such file or directory '/Users/matrix/workspace/SAGN-NUE/app/controllers/achievement/unlocks_controller.rb'
  at Error (native)
  at Object.fs.renameSync (fs.js:639:18)
  at Object.fsPlus.moveSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:221:17)
  at TreeView.module.exports.TreeView.pasteEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:926:32)
  at space-pen-div.atom.commands.add.tree-view:paste (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:270:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:70:67)
  at EventEmitter.emit (events.js:119:17)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:141:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -4:16.5 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -4:14.8 core:confirm (atom-text-editor.editor.mini)
  2x -0:44.7 core:close (atom-text-editor.editor)
     -0:43.9 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:42.9 core:confirm (atom-text-editor.editor.mini)
  9x -0:41.8 core:move-down (atom-text-editor.editor)
  3x -0:41.0 core:move-up (atom-text-editor.editor)
     -0:30.5 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment]
Looks very similar to https://github.com/atom/tree-view/issues/316. Can you please describe what you were doing to trigger this error? 

@benogle if you think this is the same things as https://github.com/atom/tree-view/issues/316 (you had a theory why this was happening), we might round them up into a single issue?

**Comment by izuzak** [comment]
Also see https://github.com/atom/tree-view/issues/356 and https://github.com/atom/tree-view/issues/364

**Comment by izuzak** [comment]
Ahhh, #356 explains the steps to reproduce this:

> 1. Copy file in Tree View
> 2. Delete file
> 3. Paste file in parent directory

Closing this in favor of #356
