### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by zenln** [atom/tree-view#362]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.172.0
**System**: linux 3.17.8-300.fc21.x86_64
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.147.0

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /usr/local/share/atom/resources/app/src/project.js:360

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/usr/local/share/atom/resources/app/src/project.js:360:15)
  at Project.module.exports.Project.bufferForPath (/usr/local/share/atom/resources/app/src/project.js:337:63)
  at Project.module.exports.Project.open (/usr/local/share/atom/resources/app/src/project.js:291:19)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/local/share/atom/resources/app/src/workspace.js:487:29)
  at Workspace.module.exports.Workspace.open (/usr/local/share/atom/resources/app/src/workspace.js:414:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/usr/local/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/usr/local/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/usr/local/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/usr/local/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/usr/local/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
  4x -0:14.3 editor:newline (atom-text-editor.editor)
  3x -0:00.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "tree-view": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Please update Atom to the latest version (currently 0.177.0) and see #307 for more details.
