### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '{filepath}.css'

### ISSUE THREAD

**Issue by anthonymonori** [atom/tree-view#370]
[Enter steps to reproduce below:]

1. Select and **cut** the contents of a folder
2. Paste it to the parent directory

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.147.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '{filepath}.css'

```
At fs.js:580

Error: ENOENT, no such file or directory '{filepath}.css'
  at Error (native)
  at Object.fs.renameSync (fs.js:580:18)
  at Object.fsPlus.moveSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:221:17)
  at TreeView.module.exports.TreeView.pasteEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:859:32)
  at space-pen-div.atom.commands.add.tree-view:paste (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:250:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:70:67)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)
  at Ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:138:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:59.1 emmet:insert-formatted-line-break-only (atom-text-editor.editor.javascript.html)
     -0:59.1 editor:newline (atom-text-editor.editor.javascript.html)
     -0:58.8 core:move-up (atom-text-editor.editor.javascript.html)
     -0:58.6 core:paste (atom-text-editor.editor.javascript.html)
     -0:58.2 core:save (atom-text-editor.editor.javascript.html)
     -0:52.7 core:move-right (atom-text-editor.editor.mini)
     -0:51.7 core:confirm (atom-text-editor.editor.mini)
     -0:41.7 core:move-down (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -0:36.9 emmet:insert-formatted-line-break-only (atom-text-editor.editor.html.null.grammar)
     -0:36.9 editor:newline (atom-text-editor.editor.html.null.grammar)
  3x -0:33.2 core:save (atom-text-editor.editor.html.null.grammar)
  3x -0:12.7 core:copy (atom-text-editor.editor.html.null.grammar)
  3x -0:10.1 tree-view:paste (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -0:02.5 core:paste (atom-text-editor.editor.html.null.grammar)
  2x -0:00.3 core:backspace (atom-text-editor.editor.html.null.grammar)
  5x -0:00.0 core:save (atom-text-editor.editor.html.null.grammar)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "welcome",
      "metrics",
      "feedback",
      "exception-reporting"
    ],
    "themes": [
      "atom-light-ui",
      "monokai"
    ],
    "projectHome": "/Users/anthonymonori/Projects"
  }
}
```

### Installed Packages

```coffee
# User
atom-charcode, v0.2.1
color-picker, v1.4.4
emmet, v2.3.3
jenkins-dashboard, v0.2.0
jsonlint, v0.4.0
language-arduino, v0.2.1
language-jade, v0.3.0
monokai, v0.12.0
travis-ci-status, v0.11.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment]
> Select and cut the contents of a folder
> Paste it to the parent directory

I'm having trouble reproducing this, @anthonymonori. 

Can you update Atom to the [latest version](https://github.com/atom/atom/releases/latest) (0.179.0), start Atom in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode) and then try to reproduce the problem by following the instructions you provided? If you're able to reproduce the problem, could you record a GIF and add it in a comment below? Thanks!

**Comment by anthonymonori** [comment]
> Can you update Atom to the latest version (0.179.0)

That solved the issue - sorry for not thinking of that sooner!

**Comment by izuzak** [comment]
@anthonymonori Actually, I think the steps to reproduce you listed weren't what actually caused the exception. I'm able to reproduce the issue you reported, but in a different way:

1. Cut the contents of a folder
2. Delete one of the items you cut
3. Paste somewhere else

I think this is a duplicate of https://github.com/atom/tree-view/issues/356, which is basically the same but uses `copy` instead of `cut`.

Thanks for your help in investigating this!
