### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/glob/node_modules/minimatch/node_modules/sigmund/sigmund.js'

### ISSUE THREAD

**Issue by m-wilson** [atom/tree-view#377]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.154.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/glob/node_modules/minimatch/node_modules/sigmund/sigmund.js'

```
At fs.js:570

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/glob/node_modules/minimatch/node_modules/sigmund/sigmund.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:136:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/node_modules/minimatch/minimatch.js:38:15
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/node_modules/minimatch/minimatch.js:1057:3)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at TreeView.module.exports.TreeView.loadIgnoredPatterns (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:467:21)
  at TreeView.module.exports.TreeView.updateRoot (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:500:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:319:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.setPaths (/Applications/Atom.app/Contents/Resources/app/src/project.js:217:27)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:38:25)
  at EventEmitter.emit (events.js:119:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-light-theme"
    ]
  },
  "tree-view": {
    "hideVcsIgnoredFiles": true,
    "hideIgnoredNames": true
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.2.1
color-picker, v1.4.4
django-templates, v0.3.0
language-django, v0.1.1
language-julia, v2.0.0
language-python-django-templates, v0.1.0
linter, v0.11.1
minimap, v4.2.2
project-manager, v1.15.5
script, v2.16.0
tree-ignore, v0.2.5

# Dev
No dev packages
```

**Comment by izuzak** [comment]
This reminds me of https://github.com/atom/release-notes/issues/29, I'm guessing it's the same underlying problem.

@m-wilson Can you reproduce the issue? Can you explain when the issue happened exactly? Also, you might want to upgrade to Atom 0.181.0 released yesterday.

cc @kevinsawicki as I'm unsure who else might have an idea about why this is happening.

**Comment by kevinsawicki** [comment]
This should be fixed now that [asar support in Atom](https://github.com/atom/atom/pull/6313) has shipped. Please comment if it happens again on Atom 0.194.0+.
