### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by halflings** [atom/tree-view#387]
1. Start with an empty Tree View (just opened the app)
2. Run the command "Tree View: Add Folder"
3. Give it any folder name (gave it "~/workspace")

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.162.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:472

TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:472:13)
  at AddDialog.module.exports.AddDialog.onConfirm (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/add-dialog.js:43:24)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/dialog.js:48:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:22.2 grammar-selector:show (atom-text-editor.editor)
     -0:20.2 core:confirm (atom-text-editor.editor.mini)
     -0:18.9 command-palette:toggle (atom-text-editor.editor)
     -0:17.5 core:select-all (atom-text-editor.editor.mini)
     -0:16.2 core:confirm (atom-text-editor.editor.mini)
     -0:16.2 script:run (atom-text-editor.editor)
     -0:14.3 command-palette:toggle (atom-text-editor.editor)
     -0:11.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:11.1 core:cancel (atom-text-editor.editor.mini)
     -0:10.2 script:run (atom-text-editor.editor)
     -0:07.8 command-palette:toggle (atom-text-editor.editor)
     -0:05.3 core:confirm (atom-text-editor.editor.mini)
     -0:05.3 tree-view:add-folder (atom-text-editor.editor)
     -0:01.8 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:00.8 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.4 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "useReactEditor": true
  },
  "tree-view": {
    "showOnRightSide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v1.5.0
atom-lint, v0.20.0
color-picker, v1.4.4
command-logger, v0.22.0
editor-stats, v0.17.0
linter, v0.10.1
linter-javac, v0.1.3
project-manager, v1.15.5
script, v2.18.0
travis-ci-status, v0.11.2

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
@maxbrunsfeld do you think this is multi-folder related?
