### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by ondrejd** [atom/tree-view#390]
Uncaught TypeError: Cannot read property 'destroy' of null

**Atom Version**: 0.158.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.138.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:350

TypeError: Cannot read property 'destroy' of null
  at TreeView.module.exports.TreeView.detach (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:350:17)
  at TreeView.module.exports.TreeView.onSideToggled (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:1018:12)
  at /usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:316:24
  at /usr/share/atom/resources/app/src/config.js:581:20
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app/src/config.js:556:29)
  at Config.module.exports.Config.set (/usr/share/atom/resources/app/src/config.js:189:14)
  at toggleConfig (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:37:24)
  at TreeView.module.exports.TreeView.toggleSide (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:984:14)
  at atom-workspace.disposables.add.atom.commands.add.tree-view:toggle-side (/usr/share/atom/resources/app/node_modules/tree-view/lib/main.js:59:39)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

/cc @atom/core

**Comment by izuzak** [comment]
You seem to be using a really old version of Atom. Can you try updating to the latest version and see if that helps? https://github.com/atom/atom/releases/latest

**Comment by izuzak** [comment]
Also, if you can still reproduce this, please create a new issue as it will contain much more debugging information than this one. And if you could add steps to reproduce -- that would be :sparkles:.

**Comment by blacRose** [comment]
I get this error if the Remote-FTP package is hiding the tree view sidebar by default.

Uncaught TypeError: Cannot read property 'destroy' of null
    /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:439

TypeError: Cannot read property 'destroy' of null
    at TreeView.module.exports.TreeView.detach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:439:17)
    at hideLocalTree (/Users/user/.atom/packages/Remote-FTP/lib/views/tree-view.js:9:65)
    at TreeView.module.exports.TreeView.attach (/Users/user/.atom/packages/Remote-FTP/lib/views/tree-view.js:213:4)
    at /Users/user/.atom/packages/Remote-FTP/lib/remote-ftp.js:58:20
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)

**Comment by maximumver** [comment]
I am getting this with Remote-FTP package too.
