### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/paulius/Projects/cs-tool/db/migrate/20150302095716_create_agents.rb'

### ISSUE THREAD

**Issue by pdambrauskas** [atom/tree-view#392]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.154.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/paulius/Projects/cs-tool/db/migrate/20150302095716_create_agents.rb'

```
At fs.js:503

Error: ENOENT, no such file or directory '/Users/paulius/Projects/cs-tool/db/migrate/20150302095716_create_agents.rb'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at TreeView.module.exports.TreeView.pasteEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:922:58)
  at space-pen-div.atom.commands.add.tree-view:paste (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:270:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:70:67)
  at EventEmitter.emit (events.js:119:17)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:141:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -5:22.4 editor:newline (atom-text-editor.editor)
     -5:11.3 core:copy (atom-text-editor.editor)
     -5:09.7 core:paste (atom-text-editor.editor)
     -4:27.1 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -4:25.2 core:confirm (atom-text-editor.editor.mini)
  3x -4:08.9 core:backspace (atom-text-editor.editor)
  2x -3:11.7 core:save (atom-text-editor.editor)
  4x -2:29.8 core:backspace (atom-text-editor.editor.mini)
     -2:27.6 core:confirm (atom-text-editor.editor.mini)
     -2:16.4 core:save (atom-text-editor.editor)
     -2:14.1 core:copy (atom-text-editor.editor)
  2x -2:13.7 core:save (atom-text-editor.editor)
     -0:57.2 tree-view:copy (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:21.2 core:confirm (atom-text-editor.editor.mini)
     -0:17.9 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:05.5 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "demisx-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
demisx-light-syntax, v0.3.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Could you please share some reproduction steps if possible?  In addition, could you try upgrading to the latest Atom version (currently 0.184.0) and see if you can still reproduce this?

**Comment by pdambrauskas** [comment]
It occurs when trying to paste file, which was deleted after copying it.

**Comment by 50Wliu** [comment]
I believe this was fixed in the latest version of Atom.
