### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/Users/s0.kubota'

### ISSUE THREAD

**Issue by kubosho** [atom/tree-view#409]
[Enter steps to reproduce below:]

1. file copy
2. file paste

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.168.0

### Stack Trace

Uncaught Error: EACCES, permission denied '/Users/s0.kubota'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/node_modules/mkdirp/index.js:74

Error: EACCES, permission denied '/Users/s0.kubota'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:752:18)
  at sync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
  at Function.sync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:245:14)
  at TreeView.module.exports.TreeView.pasteEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:965:32)
  at space-pen-div.atom.commands.add.tree-view:paste (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:277:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:02.8 tree-view:copy (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.3 tree-view:paste (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "emmet",
      "filetype-color"
    ],
    "projectHome": "/Users/s.kubota/src",
    "audioBeep": false,
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "tree-view": {
    "hideVcsIgnoredFiles": true
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.4.3
auto-update-packages, v0.2.2
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
autocomplete-snippets, v1.2.0
editorconfig, v0.3.3
file-icons, v1.5.2
japanese-wrap, v0.2.4
javascript-snippets, v1.0.0
language-asciidoc, v0.11.1
language-typescript, v0.15.0
linter, v0.12.0
linter-tslint, v0.2.1
project-manager, v1.15.5
typescript-atomizer, v0.3.1
vim-mode, v0.40.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Noticed this again in https://github.com/atom/tree-view/issues/438

**Comment by izuzak** [comment]
Also reminds me of https://github.com/atom/tree-view/issues/416.

**Comment by kubosho** [comment]
@izuzak 

My home directory name is image below:
![screenshot 2015-05-13 23 52 29](https://cloud.githubusercontent.com/assets/430267/7613390/53b9d954-f9cb-11e4-8989-2564c137f329.png)

**Comment by Athas1980** [comment]
Having similar issues. 

On linux mint, error message 

Unable to paste paths: /home/21fifty.local/achesonw/workspace-git/deploy/roles/proxy/templates/proxy.conf.internal.j2
EACCES: permission denied, mkdir '/home/21fifty0.local'

Note that in my case and I suspect in the two linked issues the path has an extra 0 in it. It seems that its not handling paste if the home folder contains a . (period) character.

Thats my guess anyway.

**Comment by 50Wliu** [comment]
I got this error (more specifically, a warning since it's been downgraded) while copy/pasting as well a few weeks ago.  My home folder also has an (unintentional) period in the middle of it.

Windows 10 x64, probably around Atom 1.0.2 or so when it occurred.

**Comment by Maxwell2022** [comment]
Same here using `1.0.19` (latest). Only with copy/paste, creating a new file is working fine.
