### ISSUE TITLE
Uncaught Error: EIO, i/o error '/home/user/IdeaProjects/Try/web/index.xhtml'

### ISSUE THREAD

**Issue by smehemmed** [atom/tree-view#412]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.168.0

### Stack Trace

Uncaught Error: EIO, i/o error '/home/user/IdeaProjects/Try/web/index.xhtml'

```
At /opt/atom/resources/app/src/workspace.js:518

Error: EIO, i/o error '/home/user/IdeaProjects/Try/web/index.xhtml'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Project.module.exports.Project.open (/opt/atom/resources/app/src/project.js:423:27)
  at Workspace.module.exports.Workspace.openURIInPane (/opt/atom/resources/app/src/workspace.js:500:31)
  at Workspace.module.exports.Workspace.open (/opt/atom/resources/app/src/workspace.js:426:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:710:31)
  at TreeView.module.exports.TreeView.entryClicked (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:427:18)
  at tree-view-file.<anonymous> (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:178:26)
  at space-pen-div.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/opt/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -0:23.9 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi, can you please share what you were doing at the time of this error please?  If you can make the error happen consistently, could you please share some reproduction steps?  Thanks :).

**Comment by smehemmed** [comment]
duiring my java JSF project
