### ISSUE TITLE
Uncaught RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes

### ISSUE THREAD

**Issue by Kuberchaun** [atom/tree-view#424]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.168.0
### Stack Trace

Uncaught RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes

```
At buffer.js:164

RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes
  at checked (buffer.js:164:11)
  at fromNumber (buffer.js:56:51)
  at new Buffer (buffer.js:41:5)
  at Object.fs.readFileSync (fs.js:416:16)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at Object.fsPlus.copySync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:302:24)
  at Object.fsPlus.copySync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:300:32)
  at Object.fsPlus.copySync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:300:32)
  at Object.fsPlus.copySync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:300:32)
  at Object.fsPlus.copySync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:300:32)
  at TreeView.module.exports.TreeView.pasteEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:963:32)
  at space-pen-div.atom.commands.add.tree-view:paste (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:277:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:552:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:392:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```
### Commands

```
  3x -5:04.7 core:backspace (atom-text-editor.editor)
     -4:58.9 core:save (atom-text-editor.editor)
     -0:06.6 tree-view:copy (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -0:01.6 tree-view:paste (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.8.0
dash, v1.1.0
file-icons, v1.5.3
git-projects, v1.13.0
jsonpp, v0.0.6
language-docker, v1.1.3
language-gradle, v0.0.3
language-powershell, v2.0.0
language-puppet, v0.11.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@henkbl Can you share more information about reproducing this problem? Can you reliably reproduce and reproduce in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Are you perhaps working with remote files?

**Comment by Tyriar** [comment]
[Looks like copying and pasting a file that pushes node.js beyond its memory limits](http://stackoverflow.com/questions/29766868/node-js-read-big-file-with-fs-readfilesync). I guess the correct thing to do is prevent opening a file of such a size (which would cause Atom to lock up anyway). Not sure how to get said limit from node or what a good limit would be.
