### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/home/matt/projects/ncm/lib/tasks/node.rake'

### ISSUE THREAD

**Issue by Trickierstinky** [atom/tree-view#425]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: linux 3.13.0-49-generic
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.148.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/home/matt/projects/ncm/lib/tasks/node.rake'

```
At fs.js:580

Error: ENOENT, no such file or directory '/home/matt/projects/ncm/lib/tasks/node.rake'
  at Error (native)
  at Object.fs.renameSync (fs.js:580:18)
  at Object.fsPlus.moveSync (/usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:221:17)
  at TreeView.module.exports.TreeView.pasteEntries (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:859:32)
  at space-pen-div.atom.commands.add.tree-view:paste (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:250:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/usr/share/atom/resources/app/src/space-pen-extensions.js:64:23)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:70:67)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)
  at Ipc.sendSync (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:39:29)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:141:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "graphite-ui",
      "seti-syntax"
    ],
    "autoHideMenuBar": true
  },
  "tree-view": {}
}
```

### Installed Packages

```coffee
# User
Package-Upgrader, v0.3.1
Sublime-Style-Column-Selection, v1.2.3
atom-color-highlight, v3.0.8
autocomplete-plus, v2.1.3
autocomplete-snippets, v1.2.0
color-picker, v1.6.0
docblockr, v0.6.3
editorconfig, v0.3.3
emmet, v2.3.7
feedback, v0.38.0
file-icons, v1.5.1
git-log, v0.3.0
git-tab-status, v1.7.0
graphite-ui, v0.14.1
grunt-runner, v0.8.0
highlight-line, v0.10.1
language-SCSS, v0.2.0
language-asp, v1.0.0
language-aspx, v0.2.0
language-csharp, v0.5.0
language-cshtml, v0.1.0
linter, v0.12.0
seti-syntax, v0.3.3
sync-settings, v0.2.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Hi, could you please update to 0.190.0 and see if this still happens?  If so, could you please try to reproduce it in safe mode (`atom --safe`)?  Finally, if it still errors, please share some reproduction steps with us.  Thanks.

**Comment by Trickierstinky** [comment]
Hi I've upgraded, used safemode and it is still happening.

I basically copied a file from file explorer then tried pasting it into a folder using the Node tree view.

**Comment by mnquintana** [comment]
What OS are you on? (I see Linux, but which specifically?)

**Comment by Trickierstinky** [comment]
Hi

I am on Ubuntu 14.04.2 LTS
