### ISSUE TITLE
Uncaught Error: EACCES: permission denied, mkdir '/Users/xxx0.yyy'

### ISSUE THREAD

**Issue by am-gd-cz** [atom/tree-view#448]
[Enter steps to reproduce below:]

1. Opened a folder with files (git repo)
2. Selected one file in tree
3. Tried Option-C/Option-V to clone file -> got an error

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.171.0

### Stack Trace

Uncaught Error: EACCES: permission denied, mkdir '/Users/andrej0.misustin'

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:74

Error: EACCES: permission denied, mkdir '/Users/andrej0.misustin'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:791:18)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at Function.sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:278:14)
  at TreeView.module.exports.TreeView.pasteEntries (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:965:32)
  at space-pen-div.atom.commands.add.tree-view:paste (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:277:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:03.1.0 tree-view:copy (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:02.7.0 tree-view:paste (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-objective-c",
      "language-php",
      "language-csharp",
      "language-go"
    ],
    "themes": [
      "darkula-ui",
      "darkula-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.1
cucumber, v0.5.0
darkula-syntax, v0.3.0
darkula-ui, v0.1.0
git-tab-status, v1.7.0
jshint, v1.3.6
language-gherkin, v1.0.2
language-puppet, v0.12.0
restore-windows, v0.4.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Looks similar to #124.
