### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by karengertrude** [atom/tree-view#483]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.172.0
**System**: Microsoft Windows 8.1
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.147.0

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\src\project.js:360

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\src\project.js:360:15)
  at Project.module.exports.Project.bufferForPath (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\src\project.js:337:63)
  at Project.module.exports.Project.open (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\src\project.js:291:19)
  at Workspace.module.exports.Workspace.openURIInPane (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\src\workspace.js:487:29)
  at Workspace.module.exports.Workspace.open (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\src\workspace.js:414:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\node_modules\tree-view\lib\tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\node_modules\tree-view\lib\tree-view.js:383:18)
  at tree-view-file.<anonymous> (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\node_modules\tree-view\lib\tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4676:9)
  at space-pen-div.elemData.handle (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4360:46)
  at Ipc.sendSync (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\atom\renderer\api\lib\ipc.js:39:29)
  at BrowserWindow.RemoteMemberFunction [as getSize] (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\atom\renderer\api\lib\remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\src\atom.js:501:29)
  at Atom.module.exports.Atom.storeDefaultWindowDimensions (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\src\atom.js:533:25)
  at c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\src\window-event-handler.js:95:21
  at handler (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\src\space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at elemData.handle (c:\Users\Karen\AppData\Local\atom\app-0.172.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by mnquintana** [comment]
You're running an extremely, extremely old version Atom - please update to the latest version (0.210.0).
