### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by kwiiby** [atom/tree-view#495]
When I right-click on left side menu in a file/folder for "Show in explorer" this is happening.

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.172.0

### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At C:\Users\Juliano\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:260

Error: spawn UNKNOWN
    at exports._errnoException (util.js:734:11)
    at ChildProcess.spawn (child_process.js:1145:11)
    at Object.exports.spawn (child_process.js:977:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (C:\Users\Juliano\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:188:44)
    at new BufferedProcess (C:\Users\Juliano\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:50:14)
    at TreeView.module.exports.TreeView.showSelectedEntryInFileManager (C:\Users\Juliano\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:835:14)
    at space-pen-div.atom.commands.add.tree-view:show-in-file-manager (C:\Users\Juliano\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:287:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Juliano\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Juliano\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Juliano\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:156:19)
```

### Commands

```
     -0:50.9.0 core:save-as (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:19.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:18.8.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:15.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.6.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
What version of Windows are you using?

**Comment by kwiiby** [comment]
Windows 8.1 Pro
