### ISSUE TITLE
Uncaught Error: ENOENT,  not found in /usr/share/atom/resources/app.asar

### ISSUE THREAD

**Issue by googlaev** [atom/tree-view#522]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04.2
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.177.0

### Stack Trace

Uncaught Error: ENOENT,  not found in /usr/share/atom/resources/app.asar

```
At /usr/share/atom/resources/app.asar/src/workspace.js:466

Error: ENOENT,  not found in /usr/share/atom/resources/app.asar
  at createNotFoundError (ATOM_SHELL_ASAR.js:101:13)
  at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:156:25)
  at ReadStream.open (fs.js:1668:6)
  at new ReadStream (fs.js:1655:10)
  at Object.fs.createReadStream (fs.js:1610:10)
  at File.module.exports.File.read (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:295:27)
  at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1027:61)
  at TextBuffer.module.exports.TextBuffer.load (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1046:19)
  at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app.asar/src/project.js:456:21)
  at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app.asar/src/project.js:431:63)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app.asar/src/project.js:393:19)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:449:31)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:375:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:709:31)
  at TreeView.module.exports.TreeView.entryClicked (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:427:18)
  at tree-view-file.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:178:26)
  at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -1:28.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:25.8.0 settings-view:view-installed-packages (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:19 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:15.3.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "archive-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.10
git-go, v1.0.1
hide-tree, v0.0.4
language-scala, v1.1.3
linter, v1.2.3
linter-scalac, v0.3.4
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by colin-kiegel** [comment]
https://github.com/atom/atom/issues/6140
