### ISSUE TITLE
Uncaught TypeError: Cannot read property 'entries' of undefined

### ISSUE THREAD

**Issue by chrisyip** [atom/tree-view#528]
[Enter steps to reproduce below:]

1. Switch Git branch from a branch that contains huge diff

**Atom Version**: 1.0.2
**System**: Mac OS X 10.11
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.177.0

### Stack Trace

Uncaught TypeError: Cannot read property 'entries' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:247

TypeError: Cannot read property 'entries' of undefined
  at Directory.module.exports.Directory.getEntries (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:247:57)
  at Directory.module.exports.Directory.reload (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:304:20)
  at PathWatcher.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:211:30)
  at HandleWatcher.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:132:26)
  at emitThree (events.js:97:13)
  at HandleWatcher.emit (events.js:172:7)
  at HandleWatcher.onEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:60:23)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:20:41

```

### Commands

```
     -5:55.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:54.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:53.7.0 core:select-up (atom-text-editor.editor.is-focused)
     -5:53.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:53 core:move-right (atom-text-editor.editor.is-focused)
     -5:52.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -5:43.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:42.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:42.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  3x -5:41.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:41.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:40.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -5:40.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:38.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  3x -5:37.7.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -5:36.8.0 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "autosave",
      "welcome",
      "atom-ctags",
      "go-plus",
      "release-notes",
      "emmet",
      "package-generator",
      "update-package-dependencies"
    ],
    "audioBeep": false
  },
  "tree-view": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-beautify, v0.28.8
autocomplete-modules, v1.0.0
autocomplete-paths, v1.0.2
color-picker, v2.0.11
docblockr, v0.7.3
editorconfig, v1.0.1
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
language-dot-template, v0.2.0
language-dustjs, v0.2.0
language-jade, v0.5.1
language-nginx, v0.5.4
linter, v1.2.4
linter-eslint, v3.0.1
minimap, v4.12.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
pigments, v0.8.4
react, v0.12.5
symbols-tree-view, v0.9.3

# Dev
No dev packages
```

**Comment by Tyriar** [comment]
Having trouble with a repro, do you mean switch branch via terminal? Couldn't repro switching between master and a branch containing a commit with 100 paragraphs of text.

**Comment by chrisyip** [comment]
Couldn't repro for now.

When I got the error, I was switching between branches that containing more than 100 commits.

**Comment by kevinsawicki** [comment]
I believe this has been fixed by https://github.com/atom/tree-view/pull/645
