### ISSUE TITLE
Uncaught Error: EACCES: permission denied, mkdir '/Users/andrew0.miller'

### ISSUE THREAD

**Issue by ikari7789** [atom/tree-view#536]
[Enter steps to reproduce below:]

I'm unsure where the "0" came from in my user name.

1. Copy file.
2. Try to paste file.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.177.0

### Stack Trace

Uncaught Error: EACCES: permission denied, mkdir '/Users/andrew0.miller'

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:74

Error: EACCES: permission denied, mkdir '/Users/andrew0.miller'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:791:18)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at Function.sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:61:24)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:278:14)
  at TreeView.module.exports.TreeView.pasteEntries (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:972:32)
  at space-pen-div.atom.commands.add.tree-view:paste (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:277:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  7x -2:06.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:57.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:56.6.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -1:54.2.0 core:move-left (atom-text-editor.editor.is-focused)
  6x -1:52.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:48.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:47.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:45.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:39.1.0 core:cut (atom-text-editor.editor.is-focused)
     -0:38.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:37.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:37.5.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:35.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:34.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:31.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-beautify, v0.28.8
color-picker, v2.0.11
minimap, v4.12.0
pigments, v0.9.0
project-manager, v1.15.11

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @ikari7789 -- I think https://github.com/atom/tree-view/pull/514 tackled this, but didn't make it into Atom 1.0.2, it will be released with Atom 1.0.3 whenever that happens. /cc @kevinsawicki for :eyes:
