### ISSUE TITLE
Uncaught Error: EIO: i/o error, close

### ISSUE THREAD

**Issue by dillonkissoon** [atom/tree-view#538]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.177.0

### Stack Trace

Uncaught Error: EIO: i/o error, close

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:466

Error: EIO: i/o error, close
    at Error (native)
    at Object.fs.closeSync (fs.js:513:18)
    at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:371:14)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:449:31)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:375:19)
    at TreeView.module.exports.TreeView.openSelectedEntry (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:709:31)
    at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:427:18)
    at tree-view-file.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:178:26)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -7:47.3.0 core:save (atom-text-editor.editor.is-focused)
     -7:33.3.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -7:33 core:backspace (atom-text-editor.editor.is-focused)
  3x -7:32 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
This was fixed by https://github.com/atom/atom/pull/7802 and will be included in Atom 1.0.3
