### ISSUE TITLE
Uncaught Error: EMFILE: too many open files, open 'C:\GitHub\vis-ma-vie\back\routes\availabilitie...

### ISSUE THREAD

**Issue by juliengony** [atom/tree-view#580]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.16
**System**: Microsoft Windows 8 Enterprise
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.187.0

### Stack Trace

Uncaught Error: EMFILE: too many open files, open 'C:\GitHub\vis-ma-vie\back\routes\availabilities.js'

```
At C:\Users\U8019341\AppData\Local\atom\app-1.0.16\resources\app.asar\src\workspace.js:476

Error: EMFILE: too many open files, open 'C:\GitHub\vis-ma-vie\back\routes\availabilities.js'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Project.module.exports.Project.open (C:\Users\U8019341\AppData\Local\atom\app-1.0.16\resources\app.asar\src\project.js:379:27)
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\U8019341\AppData\Local\atom\app-1.0.16\resources\app.asar\src\workspace.js:453:31)
  at Workspace.module.exports.Workspace.open (C:\Users\U8019341\AppData\Local\atom\app-1.0.16\resources\app.asar\src\workspace.js:379:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (C:\Users\U8019341\AppData\Local\atom\app-1.0.16\resources\app.asar\node_modules\tree-view\lib\tree-view.js:731:31)
  at TreeView.module.exports.TreeView.entryClicked (C:\Users\U8019341\AppData\Local\atom\app-1.0.16\resources\app.asar\node_modules\tree-view\lib\tree-view.js:457:18)
  at tree-view-file.<anonymous> (C:\Users\U8019341\AppData\Local\atom\app-1.0.16\resources\app.asar\node_modules\tree-view\lib\tree-view.js:183:26)
  at space-pen-div.jQuery.event.dispatch (C:\Users\U8019341\AppData\Local\atom\app-1.0.16\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-div.elemData.handle (C:\Users\U8019341\AppData\Local\atom\app-1.0.16\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -8:20 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -8:20 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -8:19 core:save (atom-text-editor.editor.is-focused)
     -7:43.9.0 node-debugger:start-resume (atom-text-editor.editor.is-focused)
 19x -7:10.2.0 node-debugger:toggle-breakpoint (atom-text-editor.editor.is-focused)
     -5:50.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -5:48.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:42.6.0 node-debugger:toggle-breakpoint (atom-text-editor.editor)
  2x -5:32.9.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:12.2.0 node-debugger:stop (atom-text-editor.editor.is-focused)
 18x -5:07.1.0 node-debugger:toggle-breakpoint (atom-text-editor.editor.is-focused)
     -3:31.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:14.6.0 node-debugger:start-resume (atom-text-editor.editor.is-focused)
     -2:59.3.0 node-debugger:stop (button.btn.btn-error)
     -2:58.2.0 node-debugger:start-resume (atom-text-editor.editor.is-focused)
 10x -2:49.3.0 node-debugger:toggle-breakpoint (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-puppet-lint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
atom-html-preview, v0.1.11
atom-pair, v2.0.10
atom-runner, v2.4.3
atom-trello, v0.1.1
atom-yamljson, v0.2.3
auto-indent, v0.5.0
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.1.0
autocomplete-plus-python-jedi, v0.3.6
build, v0.46.0
coffee-navigator, v0.0.16
colorful-json, v1.0.0
compare-files, v0.6.2
express-complete, v0.2.0
file-icons, v1.6.9
git-log, v0.4.1
git-tab-status, v1.9.2
go-plus, v3.5.1
grunt-runner, v0.11.0
language-elixir, v0.5.2
language-fsharp, v0.8.4
language-generic-config, v0.2.0
language-gherkin, v1.0.2
language-gitignore, v0.2.0
language-log, v0.6.0
language-mscript, v0.2.2
language-r, v0.2.0
language-sln, v0.1.0
linter, v1.6.0
linter-coffeelint, v1.1.0
linter-cpplint, v0.1.4
linter-csslint, v1.0.5
linter-dartanalyzer, v0.3.2
linter-htmlhint, v0.1.1
linter-js-yaml, v1.1.2
linter-jscs, v3.0.0
linter-less, v2.1.0
linter-lintr, v0.0.1
linter-pylint, v1.0.0
linter-scalac, v1.1.0
linter-tidy, v1.0.1
linter-xmllint, v0.0.7
mocha, v0.0.7
node-debugger, v1.1.8
nodejs-snippets, v1.0.2
npm, v0.1.0
open-recent, v2.3.0
pdf-view, v0.27.0
pretty-json, v0.4.1
project-manager, v2.5.2
recent-projects, v0.8.8
rest-client, v0.4.0
terminal-panel, v1.14.1
visualstudio-terminals, v0.7.0
w3c-validation, v0.2.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Should be fixed with https://github.com/atom/atom/pull/8927
