### ISSUE TITLE
Uncaught TypeError: entry.getPath is not a function

### ISSUE THREAD

**Issue by bluurn** [atom/tree-view#587]
[Enter steps to reproduce below:]

1. Pressed ^0
2. Pressed Up button

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.187.0

### Stack Trace

Uncaught TypeError: entry.getPath is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:1073

TypeError: entry.getPath is not a function
  at TreeView.module.exports.TreeView.selectEntry (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:1073:33)
  at TreeView.module.exports.TreeView.moveUp (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:694:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -3:20.3.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.mini.is-focused)
     -3:19.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -3:18.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:17.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:39.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:37 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:36.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36.7.0 git-plus:push (atom-text-editor.editor)
  6x -0:20.4.0 tree-view:toggle (atom-text-editor.editor.is-focused)
  3x -0:10.5.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:08.0 tree-view:toggle-focus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:07.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:05.5.0 tree-view:toggle-focus (atom-text-editor.editor.is-focused)
  3x -0:04.8.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:04.1.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:01.3.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "execute-as-ruby",
      "placeholder-text",
      "todo-list",
      "todo-list",
      "placeholder-text",
      "autocomplete-erlang",
      "erlang-build",
      "linter-haml",
      "linter-ruby",
      "rubocop-auto-correct",
      "ruby-bundler",
      "symbols-view",
      "lisp-paredit",
      "achievements",
      "atom-runner",
      "data-atom",
      "gist",
      "language-r",
      "minimap",
      "minimap-pigments",
      "open-on-bitbucket",
      "ruby-test"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
atom-ctags, v4.3.0
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
autocomplete-ctags, v0.3.2
clojure-eval-in-repl, v1.1.0
ctags-status, v1.3.3
expand-region, v0.2.3
git-plus, v5.4.7
language-erlang, v3.0.0
language-gitignore, v0.2.0
language-haml, v0.22.3
language-mongodb, v0.2.0
language-nginx, v0.6.0
language-sml, v0.3.0
linter, v1.8.1
linter-clojure, v1.0.0
linter-csslint, v1.0.7
linter-erlc, v0.3.0
linter-scss-lint, v2.2.1
merge-conflicts, v1.3.6
pig, v1.0.0
pigments, v0.15.0
project-manager, v2.6.1
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
ruby-slim, v0.2.0
set-syntax, v0.3.0
symbol-gen, v1.0.0
symbols-tree-view, v0.10.0
travis-ci-status, v0.18.0
tree-view-git-branch, v0.0.3
tree-view-git-status, v0.2.2
wordcount, v2.3.0

# Dev
No dev packages
```

**Comment by bluurn** [comment]
This issue appeared after I have installed the tree-view-git-branch package

**Comment by bluurn** [comment]
Sorry, this report was not related to the tree-view package, I've recreated this issue here: https://github.com/olmokramer/atom-tree-view-git-branch/issues/5
