### ISSUE TITLE
Uncaught TypeError: entry.toggleExpansion is not a function

### ISSUE THREAD

**Issue by satyavh** [atom/tree-view#600]
[Enter steps to reproduce below:]

1. installed the package
2. double clicked on another branch in the tree view

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.3
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.187.0

### Stack Trace

Uncaught TypeError: entry.toggleExpansion is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:467

TypeError: entry.toggleExpansion is not a function
  at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:467:19)
  at tree-view-git-branch.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:183:26)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  4x -3:08.7.0 tree-view:toggle (atom-pane.pane.active)
     -3:06.6.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -3:04.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:34 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -2:32.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:25.9.0 settings-view:view-installed-packages (atom-text-editor.editor)
     -2:19.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:15.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:15.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:02.1.0 command-palette:toggle (div.settings-view.pane-item)
  2x -2:01.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:58.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:55.4.0 open-on-github:branch-compare (div.settings-view.pane-item)
     -1:06.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -0:45.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:43.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.0
aligner-css, v1.2.0
aligner-scss, v1.1.0
autocomplete-sass, v0.1.0
language-emblem, v0.2.0
ruby-slim, v0.2.0
tree-view-git-branch, v0.0.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This issue was moved to olmokramer/atom-tree-view-git-branch#6
