### ISSUE TITLE
Uncaught TypeError: Cannot read property 'account' of undefined

### ISSUE THREAD

**Issue by christianstanfield** [atom/tree-view#641]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.190.0

### Stack Trace

Uncaught TypeError: Cannot read property 'account' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:252

TypeError: Cannot read property 'account' of undefined
  at Directory.module.exports.Directory.getEntries (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:252:57)
  at Directory.module.exports.Directory.reload (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:309:20)
  at PathWatcher.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:216:30)
  at HandleWatcher.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:132:26)
  at emitThree (events.js:97:13)
  at HandleWatcher.emit (events.js:175:7)
  at HandleWatcher.onEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:60:23)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:20:41

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "monokai-dark"
    ],
    "disabledPackages": [
      "atom-html-preview",
      "autocomplete-paths"
    ],
    "projectHome": "/Users/Ein/Desktop"
  },
  "tree-view": {
    "hideIgnoredNames": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-eco, v0.2.0
atom-pair, v2.0.10
atom-ternjs, v0.8.4
color-picker, v2.0.13
emmet, v2.3.14
file-icons, v1.6.11
highlight-selected, v0.10.1
language-haml, v0.23.5
language-slim, v0.5.0
language-typed-coffee-script, v1.0.0
linter, v1.10.0
linter-coffeelint, v1.1.2
linter-csslint, v1.1.0
linter-jshint, v1.2.1
linter-ruby, v1.2.0
monokai-dark, v1.3.0
pigments, v0.18.1
remote-edit, v1.8.22
rspec-snippets, v0.4.0
script, v3.0.1
travis-ci-status, v0.18.0
unity-ui, v2.1.2

# Dev
No dev packages
```

**Comment by billybonks** [comment]
have you tried running atom in safe mode ?

**Comment by kevinsawicki** [comment]
Yeah, I don't see any references to `account` in `Directory.getEntries`.

Do you have any packages installed that customize the tree view?

**Comment by christianstanfield** [comment]
Hey, I've never used safe mode before, but I've noticed Atom does tend to throw errors sometimes when I move files around into new directories/folders within the app. I have file icons: https://atom.io/packages/file-icons but that's the only package effecting tree view I believe

**Comment by kevinsawicki** [comment]
Okay, I think I've figured it out, does your project has a folder named `entries` in it by any chance?

**Comment by christianstanfield** [comment]
It does yes

**Comment by kevinsawicki** [comment]
@christianstanfield great, thanks, working on a fix now

**Comment by christianstanfield** [comment]
Awesome, glad I could help. The entries folder is also a subfolder of the models directory (rails app) which is where I was moving files around.
