### ISSUE TITLE
Uncaught Error: EACCES: permission denied, scandir '/tmp/systemd-private-5733d72e58b844acac32ebc1...

### ISSUE THREAD

**Issue by pascalchevrel** [atom/tree-view#671]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0-beta0
**System**: Ubuntu 15.10
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.198.0
### Stack Trace

Uncaught Error: EACCES: permission denied, scandir '/tmp/systemd-private-5733d72e58b844acac32ebc19e0a39d4-colord.service-WGojkN'

```
At fs.js:813

Error: EACCES: permission denied, scandir '/tmp/systemd-private-5733d72e58b844acac32ebc19e0a39d4-colord.service-WGojkN'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at Object.fsPlus.listSync (/usr/share/atom-beta/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:171:18)
    at Directory.module.exports.Directory.squashDirectoryNames (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:379:23)
    at new Directory (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:28:25)
    at Directory.module.exports.Directory.getEntries (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:256:30)
    at Directory.module.exports.Directory.reload (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:312:20)
    at Directory.module.exports.Directory.expand (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:356:12)
    at tree-view-directory.DirectoryView.expand (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory-view.js:177:24)
    at tree-view-directory.DirectoryView.initialize (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory-view.js:81:21)
    at TreeView.<anonymous> (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/tree-view.js:571:16)
    at TreeView.module.exports.TreeView.updateRoots (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/tree-view.js:576:10)
    at /usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/tree-view.js:361:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Project.module.exports.Project.addPath (/usr/share/atom-beta/resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/usr/share/atom-beta/resources/app.asar/src/atom-environment.js:1029:26)
    at EventEmitter.outerCallback (/usr/share/atom-beta/resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-ruby",
      "language-ruby-on-rails",
      "metrics",
      "php-integrator-base",
      "php-integrator-autocomplete-plus",
      "php-integrator-annotations",
      "php-integrator-navigation",
      "php-integrator-tooltips",
      "php-composer-completion",
      "atom-autocomplete-php",
      "atom-php-navigation",
      "autocomplete-php",
      "php-analyser",
      "php-class-tree",
      "php-extract-method",
      "php-fmt",
      "php-introspector",
      "tasks",
      "terminal-plus",
      "project-dropdown",
      "imdone-atom",
      "imdone-atom-github",
      "nav-panel",
      "syntax-theme-auto-changer"
    ],
    "ignoredNames": [
      ".git",
      "vendor",
      ".svn",
      ".hg",
      ".idea"
    ],
    "themes": [
      "slack-ui",
      "fark-syntax"
    ]
  },
  "tree-view": {
    "hideIgnoredNames": true,
    "hideVcsIgnoredFiles": true,
    "squashDirectoryNames": true
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
aligner, v0.17.4
aligner-php, v1.0.0
autoclose-html, v0.19.0
color-picker, v2.0.14
docblockr, v0.7.3
dotlang-grammar, v0.0.1
fark-syntax, v0.1.0
file-icons, v1.6.13
file-type-icons, v0.7.4
gtk-dark-theme, v0.1.4
hidpi, v0.7.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
inline-messenger, v1.2.8
keyboard-localization, v1.4.10
language-htaccess, v0.1.1
linter, v1.11.3
minimap, v4.17.0
php-cs-fixer, v2.5.1
php-twig, v4.0.0
pigments, v0.19.1
plain-simple, v1.0.2
project-manager, v2.6.5
quick-docs, v0.1.0
save-session, v0.15.7
silverstripe-syntax-and-snippets, v0.4.0
slack-ui, v0.6.0
symbols-tree-view, v0.10.1

# Dev
No dev packages
```

**Comment by ZuBB** [comment]
also got this... and cant get rid of this.

@pascalchevrel how do solve this?

**Comment by ZuBB** [comment]
ok, today I have got this one more time and seems I know why this happens. 

for some reason I had one more dir added to project which was a `/tmp` and since there is some stuff that belongs to root only (which can be accessed for obvious reason) tree fails..

**Comment by ZuBB** [comment]
how to solve this: make everything in /tmp/systemd* accessible by everryone (`chmod -R777 /tmp/systemd*`) and then drop `tmp` folder from tree
