### ISSUE TITLE
Failed to activate the tree-view package

### ISSUE THREAD

**Issue by luca-zamboni** [atom/tree-view#675]
[Enter steps to reproduce below:]

1. After updating atom
**Atom Version**: 1.3.1
**System**: Ubuntu 15.10
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.198.0

### Stack Trace

Failed to activate the tree-view package

```
At EACCES: permission denied, scandir '/tmp/systemd-private-063cb1d2ab1a474b888b74781b75bbb4-colord.service-6jAvRV'

Error: EACCES: permission denied, scandir '/tmp/systemd-private-063cb1d2ab1a474b888b74781b75bbb4-colord.service-6jAvRV'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at Object.fsPlus.listSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:171:18)
    at Directory.module.exports.Directory.squashDirectoryNames (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:379:23)
    at new Directory (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:28:25)
    at Directory.module.exports.Directory.getEntries (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:256:30)
    at Directory.module.exports.Directory.reload (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:312:20)
    at Directory.module.exports.Directory.expand (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:356:12)
    at tree-view-directory.DirectoryView.expand (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory-view.js:177:24)
    at tree-view-directory.DirectoryView.initialize (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory-view.js:81:21)
    at TreeView.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:571:16)
    at TreeView.module.exports.TreeView.updateRoots (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:576:10)
    at TreeView.module.exports.TreeView.initialize (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:101:12)
    at TreeView.View [as constructor] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new TreeView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:52:45)
    at Object.module.exports.createView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:134:25)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:51:14)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:170:19)
    at /usr/share/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:517:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:686:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "linter-flake8"
    ]
  },
  "tree-view": {
    "hideIgnoredNames": true,
    "squashDirectoryNames": true,
    "hideVcsIgnoredFiles": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.2.3
browser-plus, v0.0.54
file-icons, v1.6.13
highlight-selected, v0.11.1
indent-guide-improved, v1.4.5
language-latex, v0.6.1
latex, v0.28.2
linter, v1.11.3
minimap, v4.18.0
pigments, v0.19.3
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by Yajo** [comment]
I just got hit by this, why is it closed?
Atom 1.7.4

**Comment by fidalgo** [comment]
@Yajo I have it also. Here is the stack trace:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at Object.shouldAttach (/usr/lib64/atom/node_modules/tree-view/lib/main.js:114:23)
    at Object.activate (/usr/lib64/atom/node_modules/tree-view/lib/main.js:16:16)
    at Package.module.exports.Package.activateNow (/usr/lib64/atom/src/package.js:183:20)
    at /usr/lib64/atom/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/lib64/atom/src/package.js:92:15)
    at /usr/lib64/atom/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/lib64/atom/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib64/atom/src/package-manager.js:530:21)
    at /usr/lib64/atom/src/package-manager.js:511:29
    at Config.module.exports.Config.transactAsync (/usr/lib64/atom/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/lib64/atom/src/package-manager.js:506:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/lib64/atom/src/package-manager.js:489:46)
    at /usr/lib64/atom/src/atom-environment.js:754:28
```

**Comment by sebastiaanfranken** [comment]
Same issue as @fidalgo above. Here's my stack trace:
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at Object.shouldAttach (/usr/lib64/atom/node_modules/tree-view/lib/main.js:114:23)
    at Object.activate (/usr/lib64/atom/node_modules/tree-view/lib/main.js:16:16)
    at Package.module.exports.Package.activateNow (/usr/lib64/atom/src/package.js:183:20)
    at /usr/lib64/atom/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/lib64/atom/src/package.js:92:15)
    at /usr/lib64/atom/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/lib64/atom/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib64/atom/src/package-manager.js:530:21)
    at /usr/lib64/atom/src/package-manager.js:511:29
    at Config.module.exports.Config.transactAsync (/usr/lib64/atom/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/lib64/atom/src/package-manager.js:506:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/lib64/atom/src/package-manager.js:489:46)
    at /usr/lib64/atom/src/atom-environment.js:754:28
```

**Comment by Lechindianer** [comment]
Same issue here as @sebastiaanfranken and @fidalgo already described. Happens when I change to dir **/home/user/test** and run
> atom $PWD 

While
> atom /home/user/test
works perfectly

**Comment by 50Wliu** [comment]
@fidalgo @sebastiaanfranken @Lechindianer Can one of you open a new issue for this?

**Comment by alex94puchades** [comment]
Did someone open a new issue for this? I'm having the same issue here (backtrace similar to that of @fidalgo) whenever I invoke atom from the command line with a path

**Comment by m-czernek** [comment]
+1, same issue.

**Comment by fusion809** [comment]
Are any of yas using a build of Atom that uses a version of Electron > 0.36.x? If you are using Arch Linux and the [atom] repository of [tensor5](https://github.com/tensor5/arch-atom).

**Comment by alex94puchades** [comment]
I'm using the [mosquito/atom](https://copr.fedorainfracloud.org/coprs/mosquito/atom/) copr for Fedora 24.
