### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by AlinV12** [atom/tree-view#700]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Ubuntu 14.04.3
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.198.0

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At path.js:8

TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:477:5)
    at MoveDialog.module.exports.MoveDialog.onConfirm (/home/alin/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/move-dialog.js:38:24)
    at space-pen-div.atom.commands.add.core:confirm (/home/alin/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/dialog.js:48:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/home/alin/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /home/alin/usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/home/alin/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/home/alin/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/home/alin/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/home/alin/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:51.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:51.2.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:51 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:49.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:48.9.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:48.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:48 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:47.3.0 core:backspace (atom-text-editor.editor.is-focused)
  6x -0:45.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:29.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:29.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:27.4.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -0:24.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
 12x -0:16.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:05.9.0 tree-view:move (span.name.icon.icon-file-text)
     -0:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.14

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @AlinV12, what were you doing when this happened?

**Comment by davidlgj** [comment]
Hi, I'm getting the same error.

To reproduce:
1. Create a empty directory (`cd /tmp && mkdir foo && cd foo`)
2. Start atom `atom .`

If I open a file by `Ctrl+p` then close atom and open it again it works and will no longer crash at startup. But it happens every single time in a new directory. 

Hope that helps, please tell me if I can do anything more to track the bug down!.

**Atom Version**: 1.7.4
**System**: linux 4.5.4-1-ARCH
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.205.0


### Stack Trace

Failed to activate the tree-view package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at Object.shouldAttach (/usr/lib/atom/node_modules/tree-view/lib/main.js:114:23)
    at Object.activate (/usr/lib/atom/node_modules/tree-view/lib/main.js:16:16)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:183:20)
    at /usr/lib/atom/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:92:15)
    at /usr/lib/atom/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:530:21)
    at /usr/lib/atom/src/package-manager.js:511:29
    at Config.module.exports.Config.transactAsync (/usr/lib/atom/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/lib/atom/src/package-manager.js:506:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/lib/atom/src/package-manager.js:489:46)
    at /usr/lib/atom/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.11.4
linter-eslint, v7.2.2

# Dev
No dev packages
```

**Comment by cjtallman** [comment]
I got this error by opening atom in the root level of my drive (E:\) and duplicated a file at the root level via the right-click on the tree view.  When prompted to specify a name for the new file, the field is pre-populated with "E:foo.txt" instead of "E:\foo.txt".  Just changing "foo" to "bar" without adding the back-slash will throw the error for me.  Adding that back-slash prevents the error for me.

**Comment by Ben3eeE** [comment]
I can reproduce this on Atom `1.12-dev-fcddf83` (Electron 1.4.1 branch)

Here is what I did:

1. Open Atom directly on `I:\` drive.
2. Close and reopen Atom (This step is because https://github.com/atom/tree-view/issues/903? restarting changes the name of the root folder to . instead of nothing)
3. Try to rename `foo.txt`, the dialog defaults to `I:foo.txt`, just change the file name and confirm the dialog.

Also it is not possible to delete files.
![image](https://cloud.githubusercontent.com/assets/1058982/19124247/ba458cbe-8b32-11e6-9ca2-11a0ac768b0f.png)

**Comment by riemers** [comment]
Tried with version 1.19.0-beta2 issue still remains. Is it not something as easy as adding a slash to it somewhere? Because if i rename the file it will error, but if i add a \ to it where X: so it will be X:\something it will work as intended.

Are there any work around?

**Comment by notridan** [comment]
I have the same issue

**Comment by Ben3eeE** [comment]
@rsese Yeah all of them are the same issue and only if you open the root of the hard drive directly. It doesn't matter if it's a network mapped Y:\ or the local C:\ drive. All of them have this issue.

If you create a folder and open that instead it works correctly. So like if you map `\\servername\path\to\projects\my-project` to `Y:\` and open that you run into this issue. If you instead map `\\servername\path\to\projects` to `Y:\` and open `Y:\my-project` it works fine.
