### ISSUE TITLE
Uncaught TypeError: selectedEntry.getPath is not a function

### ISSUE THREAD

**Issue by vforge** [atom/tree-view#736]
[Enter steps to reproduce below:]

1. right click on empty space in tree view
2. select "new folder" from the menu

**Atom Version**: 1.6.0-beta3
**System**: Mac OS X 10.11.3
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.201.1

### Stack Trace

Uncaught TypeError: selectedEntry.getPath is not a function

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:1066

TypeError: selectedEntry.getPath is not a function
    at TreeView.module.exports.TreeView.add (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:1066:69)
    at atom-workspace.disposables.add.atom.commands.add.tree-view:add-folder (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/tree-view/lib/main.js:86:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom Beta.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom Beta.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/context-menu-manager.js:172:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:13.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:13.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:12.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:12.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:12.1.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:11.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:11.2.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:10.5.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:10.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.2.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:08.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:02.4.0 tree-view:add-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.7.0 tree-view:expand-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.6.0 tree-view:toggle-vcs-ignored-files (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "seti-icons"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "tree-view": {
    "hideVcsIgnoredFiles": true
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
autoclose-html, v0.20.0
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
battery-status, v0.10.3
ctags-status, v1.3.4
docblockr, v0.7.3
editor-stats, v0.17.0
editorconfig, v1.2.4
file-icons, v1.6.14
fold-lines, v0.2.0
highlight-line, v0.11.1
highlight-selected, v0.11.2
indentation-indicator, v0.6.0
language-lua, v0.9.4
line-count-status, v0.0.3
markdown-preview-plus, v2.2.2
minimap, v4.19.0
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
open-recent, v5.0.0
pigments, v0.23.1
project-viewer, v0.2.30
rails-i18n-autocomplete, v0.3.0
remote-edit, v1.8.24
ruby-slim, v0.2.0
ssh-config, v0.10.1
statusbar-datetime, v0.9.7
terminal-plus, v0.14.5
tree-view-git-branch, v0.0.6
tree-view-git-modified, v0.6.2
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @vforge, can you try reproducing this in safe mode (`atom --safe`)?  Thanks!

**Comment by vforge** [comment]
Works fine. And I couldn't reproduce it without flag after restarting Atom without a flag again.
