### ISSUE TITLE
Failed to activate v0.206.2 Cannot find module 'electron'

### ISSUE THREAD

**Issue by oakesja** [atom/tree-view#823]
### Steps to reproduce below

1. Install the latest version, v0.206.2, of tree-view
2. Reload atom
3. tree-view fails to activate

**Atom Version**: 1.4.0
**System**: Ubuntu 14.04.4
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.206.2

### Stack Trace

Failed to activate the tree-view package

```
At Cannot find module 'electron'

Error: Cannot find module 'electron'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/joakes/.atom/packages/tree-view/lib/tree-view.coffee:2:11)
    at Object.<anonymous> (/home/joakes/.atom/packages/tree-view/lib/tree-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.createView (/home/joakes/.atom/packages/tree-view/lib/main.coffee:49:18)
    at Object.module.exports.activate (/home/joakes/.atom/packages/tree-view/lib/main.coffee:13:6)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:524:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:336:19
    at /usr/share/atom/resources/app.asar/src/config.js:623:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:808:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:600:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/usr/share/atom/resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:165:14)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:45.6.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
  6x -3:43.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:41.9.0 settings-view:open (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "save-commands"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git/*",
      ".idea/*"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/home/joakes/git"
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.23.0
file-icons, v1.7.7
language-elm, v1.3.3
line-diff-details, v1.2.0
linter, v1.11.4
linter-elm-make, v0.4.0
minimap, v4.22.1
minimap-git-diff, v4.3.0
sync-settings, v0.7.2
tree-view, v0.206.2

# Dev
No dev packages
```

**Comment by oakesja** [comment]
Updating to the latest version of atom fixes this problem.
