### ISSUE TITLE
node-gyp rebuild fails if .atom is symlinked

### ISSUE THREAD

**Issue by matthewwithanm** [atom/tree-view#83]
I don't think this is specific to tree-view, but rather common to anything that tries to run node-gyp rebuild.

I had moved my .atom folder to my dropbox and symlinked it from my home directory, but it caused `apm upgrade` to fail when tree-view ran `node-gyp rebuild`. Here's the error:

```
Installing tree-view@0.79.0 to /Users/username/.atom/packages ✗

> runas@0.5.4 install /private/var/folders/jp/14c8yrgn3tn45w01yjphvv780000gq/T/apm-install-dir-114211-10714-1xm95ho/node_modules/tree-view/node_modules/runas
> node-gyp rebuild


npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/runas
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/theorist
npm http GET https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/theorist
npm http 304 https://registry.npmjs.org/runas
npm http 304 https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/delegato
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/osenv/0.0.3
npm http GET https://registry.npmjs.org/nan/0.8.0
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/delegato
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/osenv/0.0.3
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan/0.8.0
npm http GET https://registry.npmjs.org/graceful-fs
make: *** No rule to make target `../../../../../../../../../../../../Users/username/Dropbox/Application', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.1.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/jp/14c8yrgn3tn45w01yjphvv780000gq/T/apm-install-dir-114211-10714-1xm95ho/node_modules/tree-view/node_modules/runas
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/graceful-fs
npm ERR! runas@0.5.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@0.5.4 install script.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.1.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--userconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "install" "/Users/username/.atom/.node-gyp/.atom/.apm/tree-view/0.79.0/package.tgz" "--target=0.11.10" "--arch=x64"
npm ERR! cwd /private/var/folders/jp/14c8yrgn3tn45w01yjphvv780000gq/T/apm-install-dir-114211-10714-1xm95ho
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/jp/14c8yrgn3tn45w01yjphvv780000gq/T/apm-install-dir-114211-10714-1xm95ho/npm-debug.log
npm ERR! not ok code 0
```

**Comment by 50Wliu** [comment]
Optimistically closing this after 3+ years.  @matthewwithanm if this is still a problem you can reopen it yourself :).
