### ISSUE TITLE
Uncaught TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by PwrSrg** [atom/tree-view#857]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Microsoft Windows 10 Pro
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.205.0

### Stack Trace

Uncaught TypeError: Cannot read property 'constructor' of undefined

```
At /C:/Users/Sergio/.atom/init.coffee:5

TypeError: Cannot read property 'constructor' of undefined
    at handlePanel (file:///C:/Users/Sergio/.atom/init.coffee:16:26)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at PanelContainer.module.exports.PanelContainer.addPanel (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\src\panel-container.js:69:20)
    at Workspace.module.exports.Workspace.addPanel (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\src\workspace.js:893:45)
    at Workspace.module.exports.Workspace.addLeftPanel (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\src\workspace.js:826:19)
    at TreeView.module.exports.TreeView.attach (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\tree-view\lib\tree-view.js:429:27)
    at TreeView.module.exports.TreeView.updateRoots (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\tree-view\lib\tree-view.js:589:14)
    at C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\tree-view\lib\tree-view.js:371:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Project.module.exports.Project.addPath (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\src\project.js:263:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\src\atom-environment.js:1116:26)
    at EventEmitter.outerCallback (C:\Users\Sergio\AppData\Local\atom\app-1.7.4\resources\app.asar\src\application-delegate.js:244:18)
    at emitThree (events.js:102:20)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "linter-cflint",
      "tree-view-open-files"
    ],
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v1.0.0
autoclose-html, v0.23.0
clipboard-plus, v0.5.1
emmet, v2.4.3
highlight-selected, v0.11.2
imdone-atom, v1.3.29
language-cfml, v0.12.0
less-than-slash, v0.13.0
linter, v1.11.4
linter-bootlint, v1.0.2
linter-csslint, v1.3.2
linter-htmlhint, v1.1.4
linter-jshint, v2.1.0
linter-php, v1.2.0
minimap, v4.24.3
minimap-highlight-selected, v4.4.0
monokai-seti, v0.7.0
open-recent, v5.0.0
pigments, v0.29.1
pinegrow-atom, v0.3.1
project-manager, v2.9.7
seti-ui, v1.2.3
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This is a problem with your own `init.coffee` file.
