### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidChangeStatuses' of undefined

### ISSUE THREAD

**Issue by carlosdcweb** [atom/tree-view#888]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Linux Mint
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.205.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeStatuses' of undefined

```
At /usr/share/atom/resources/app.asar/src/git-repository.js:131

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at Directory.module.exports.Directory.subscribeToRepo (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:116:42)
    at new Directory (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:51:12)
    at TreeView.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:570:23)
    at TreeView.module.exports.TreeView.updateRoots (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:587:10)
    at TreeView.module.exports.TreeView.initialize (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:106:12)
    at TreeView.View [as constructor] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new TreeView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:56:45)
    at Object.module.exports.createView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:105:25)
    at atom-workspace.disposables.add.atom.commands.add.tree-view:toggle (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:32:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:29.4.0 command-palette:toggle (atom-pane.pane.active)
     -0:27 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:27 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 tree-view:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-diff",
      "status-bar"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by ragesoss** [comment]
I'm getting this same issue after upgrading to 1.8.0 (on debian stretch).

Same problem is also present in the 1.9 beta.

**Comment by ragesoss** [comment]
I was able to get tree-view working again by removing atom and reinstalling version 1.7.3.

**Comment by ruppalsingh** [comment]
Just upgraded from Atom v1.4.0 to v1.8.0 and receiving the same error, along with another on the status-bar package.

**Comment by 50Wliu** [comment]
@ruppalsingh @ragesoss @carlosdcweb How did you install Atom?

**Comment by ruppalsingh** [comment]
I downloaded the Debian package from GitHub and ran:

`sudo dpkg --install atom-amd64.deb`

**Comment by mikefrey** [comment]
Issue appears for me on Ubuntu 16.04 running 1.8.0 installed from the GitHub Debian package.

1.9.0-beta0 installed via GitHub Debian package works.
1.7.4 installed via GitHub Debian package works.

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/12182?

**Comment by ddaza** [comment]
:+1:

**Comment by 50Wliu** [comment]
@Ben3eeE Correct: Everyone here, please subscribe to atom/atom#12182 for updates and follow the instructions in that Issue.

**Comment by carlosdcweb** [comment]
Where can I dowload the 1.7.x version in order to correct the issue.

Thanks

**Comment by ragesoss** [comment]
@carlosdcweb Download the real 1.8.0 version (or any other one from the 'releases' page on github) to correct the issue: https://github.com/atom/atom/releases/download/v1.8.0/atom-amd64.deb

The ones from the github homepage were apparently the wrong files, because of a DNS problem.

**Comment by zeandrade** [comment]
I have this issue only when I'm working in a folder with a .git repo. Using "Open Directory" with "not git" project , works fine.

**Comment by rodrigoaraujoti** [comment]
Same problem. I just update to the 1.8.0 version.

**Comment by ptytb** [comment]
I renamed ~/.atom, still having same issue. Seems roll back from 1.8.0 is the only option.

**Comment by 50Wliu** [comment]
As I said earlier, please follow the instructions provided in atom/atom#12182 to resolve this issue.
