### ISSUE TITLE
Tree-view error

### ISSUE THREAD

**Issue by jallander** [atom/tree-view#891]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Linux Mint
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.205.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeStatuses' of undefined

```
At /usr/share/atom/resources/app.asar/src/git-repository.js:131

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at Directory.module.exports.Directory.subscribeToRepo (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:116:42)
    at new Directory (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:51:12)
    at TreeView.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:570:23)
    at TreeView.module.exports.TreeView.updateRoots (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:587:10)
    at TreeView.module.exports.TreeView.initialize (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:106:12)
    at TreeView.View [as constructor] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new TreeView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:56:45)
    at Object.module.exports.createView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:105:25)
    at atom-workspace.disposables.add.atom.commands.add.tree-view:toggle (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:32:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:01.0 tree-view:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "themes": [
      "one-light-ui",
      "github-2016-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
github-2016-syntax, v1.2.0
tree-view-git-status, v1.0.2

# Dev
No dev packages
```

**Comment by jallander** [comment]
after uninstall nucleide

**Comment by 50Wliu** [comment]
Please see atom/atom#12182 for how to resolve this issue.

**Comment by jallander** [comment]
Problem is solved, thanks.
