### ISSUE TITLE
Seeing this error everytime when i am toggling tree view

### ISSUE THREAD

**Issue by maximumver** [atom/tree-view#894]
I am using Remote-FTP package
https://atom.io/packages/Remote-FTP

It has an option of auto-hide local treview when ftp view is visible.
So i've enabled it.
When i'm turn off ftp tree view with package short key, default local treeview becomes visible again.
So i toggle off it too, because i need more space. with Ctrl + \
And everything is ok.

When in second moment i'm using a shortkey to show again treeview of Remote-FTP i see this error msg. 
At first glance it does nothing to me. I am just closing this msg. But it appears again and again when i switch between toggle on/off between ftp and local trees.

Steps:
1. show ftp tree (package auto hides local treeview, there is an option)
2. hide ftp tree ( and i can see local treeview again)
3. hide local tree view too. (no active tree view now)
4. show ftp tree view ( pop-ups an error)

`TypeError: Cannot read property 'destroy' of null
    at TreeView.module.exports.TreeView.detach (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:439:17)
    at hideLocalTree (C:\Users\Admin\.atom\packages\Remote-FTP\lib\views\tree-view.js:9:65)
    at TreeView.module.exports.TreeView.attach (C:\Users\Admin\.atom\packages\Remote-FTP\lib\views\tree-view.js:213:4)
    at TreeView.module.exports.TreeView.toggle (C:\Users\Admin\.atom\packages\Remote-FTP\lib\views\tree-view.js:233:9)
    at atom-workspace.atom.commands.add.remote-ftp:toggle (C:\Users\Admin\.atom\packages\Remote-FTP\lib\remote-ftp.js:117:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)`

**Comment by mnquintana** [comment]
This is an issue with Remote-FTP – feel free to [open an issue there.](https://github.com/mgrenier/remote-ftp)
