### ISSUE TITLE
Failed to activate the tree-view package

### ISSUE THREAD

**Issue by udoyen** [atom/tree-view#895]
[Enter steps to reproduce below:]

1. create git repo on computer
2. add files and then commit
3. create and add remote repo
4. close and relaunch atom

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.205.0

### Stack Trace

Failed to activate the tree-view package

```
At Cannot read property 'onDidChangeStatuses' of undefined

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at Directory.module.exports.Directory.subscribeToRepo (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:116:42)
    at new Directory (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:51:12)
    at TreeView.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:570:23)
    at TreeView.module.exports.TreeView.updateRoots (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:587:10)
    at TreeView.module.exports.TreeView.initialize (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:106:12)
    at TreeView.View [as constructor] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new TreeView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:56:45)
    at Object.module.exports.createView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:105:25)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:22:14)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-csslint"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
emmet, v2.4.3
language-blade, v0.25.3
laravel, v0.7.0
terminal-plus, v0.14.5
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please re-download Atom 1.8.0.  Apologies for the inconvenience.

**Comment by ZuBB** [comment]
got this with latest atom. seems it happens when reopen atom with project that has been deleted..

**Comment by ZuBB** [comment]
config 

```
"*":
  "atom-beautify":
    _analyticsUserId: ..
  autosave:
    enabled: true
  core:
    autoHideMenuBar: true
    disabledPackages: [
      "autosave"
      "archive-view"
      "go-to-line"
      "language-c"
      "language-clojure"
      "language-csharp"
      "language-java"
      "language-make"
      "language-mustache"
      "language-objective-c"
      "language-perl"
      "language-php"
      "welcome"
      "language-toml"
      "language-property-list"
      "image-view"
      "bookmarks"
    ]
    projectHome: "~/work/"
  editor:
    fontSize: 21
    showIndentGuide: true
  "exception-reporting":
    userId: ..
  linter:
    errorPanelHeight: 26
  "sync-settings":
    _analyticsUserId: ...
    _lastBackupHash: ...
    gistId: ...
    personalAccessToken: ...
  "tree-view":
    hideIgnoredNames: true
    hideVcsIgnoredFiles: true
    squashDirectoryNames: true
  "vim-mode":
    useClipboardAsDefaultRegister: false
    useSmartcaseForSearch: true
  welcome:
    showOnStartup: false
  whitespace:
    ensureSingleTrailingNewline: false
```

**Comment by 50Wliu** [comment]
@ZuBB can you please open a new issue?  Thanks!

**Comment by ZuBB** [comment]
@50Wliu done. see #991
