### ISSUE TITLE
Uncaught Error: EACCES: permission denied, scandir '/tmp/systemd-private-9686778587f04320914d7bf6...

### ISSUE THREAD

**Issue by rogerbinns** [atom/tree-view#898]
Turning on tree view causes this error.  The underlying cause is that I asked Atom to edit a file in /tmp, so it decided to add /tmp as a folder, and doesn't have permissions to access all files in /tmp.

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04.1
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.205.0

### Stack Trace

Uncaught Error: EACCES: permission denied, scandir '/tmp/systemd-private-9686778587f04320914d7bf6c3f2e34e-colord.service-1bxcaB'

```
At fs.js:856

Error: EACCES: permission denied, scandir '/tmp/systemd-private-9686778587f04320914d7bf6c3f2e34e-colord.service-1bxcaB'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:497:28)
    at Object.fsPlus.listSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:171:18)
    at Directory.module.exports.Directory.squashDirectoryNames (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:388:23)
    at new Directory (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:28:25)
    at Directory.module.exports.Directory.getEntries (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:263:30)
    at Directory.module.exports.Directory.reload (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:321:20)
    at Directory.module.exports.Directory.expand (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:365:12)
    at tree-view-directory.DirectoryView.expand (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory-view.js:177:24)
    at tree-view-directory.DirectoryView.initialize (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory-view.js:81:21)
    at TreeView.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:582:16)
    at TreeView.module.exports.TreeView.updateRoots (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:587:10)
    at TreeView.module.exports.TreeView.initialize (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:106:12)
    at TreeView.View [as constructor] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new TreeView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:56:45)
    at Object.module.exports.createView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:105:25)
    at atom-workspace.disposables.add.atom.commands.add.tree-view:toggle (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:32:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:00.9.0 tree-view:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-clang"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/space",
    "themes": [
      "one-dark-ui",
      "slime"
    ]
  },
  "tree-view": {
    "hideIgnoredNames": true,
    "hideVcsIgnoredFiles": true,
    "squashDirectoryNames": true
  }
}
```

### Installed Packages

```coffee
# User
aligner-python, v1.0.1
atom-jinja2, v0.5.0
autocomplete-clang, v0.9.4
autocomplete-python, v1.8.4
bug-report, v0.7.1
clang-format, v1.25.0
language-csv, v1.1.2
language-diff, v0.4.0
language-javascript-semantic, v0.2.1
language-restructuredtext, v1.0.0
linter, v1.11.14
linter-csslint, v1.3.2
linter-eslint, v7.2.4
linter-flake8, v1.13.2
linter-javac, v1.9.4
linter-json-lint, v0.1.1
linter-rst, v0.0.3
merge-conflicts, v1.4.4
pigments, v0.31.2
python-jedi, v0.3.7
python-tools, v0.6.8
slime, v1.6.1
symbols-tree-view, v0.13.2
tablr, v1.3.2

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment]
https://github.com/atom/tree-view/issues/777?

**Comment by 50Wliu** [comment]
Closing in favor of #777 - feel free to subscribe there for updates.
