### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTime' of undefined

### ISSUE THREAD

**Issue by adam31** [atom/tree-view#927]
[Enter steps to reproduce below:]

1. clone atom from https://github.com/atom/atom.git
2. build atom with script/build
3. start atom
4. From menu select Atom->About Atom
5. Observe "Uncaught TypeError" dialog.

**Atom Version**: 1.11.0-dev-bcc0aba
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.209.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getTime' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:599

TypeError: Cannot read property 'getTime' of undefined
    at TreeView.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:599:36)
    at TreeView.module.exports.TreeView.updateRoots (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:619:10)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:369:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:270:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1147:26)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:258:18)
    at emitThree (events.js:115:20)
    at EventEmitter.emit (events.js:188:7)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.1 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.58.3 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Confirmed on 1.11.0-dev-a0f7669, Windows 10 x64.  @Alhadis this seems to be related to your fs changes.

Steps to reproduce:
1. Open Atom
2. Remove all project folders and open files
3. Reload Atom
4. Help -> About Atom

**Comment by Alhadis** [comment]
Inspecting now.

If I can see something I'll fix, I'll submit a PR to the `tree-view` repo. :)

**Comment by Alhadis** [comment]
@50Wliu Odd, the `atom://about/` view seems to be being added as a project URI when it's launched in an empty workspace. Is it meant to do that?

Either way, that's what was causing the error; it was attempting to `lstat` on a make-believe path. I didn't foresee it ever having issues reading the disk's contents, so I didn't add a check for failure...

**Comment by 50Wliu** [comment]
> Is it meant to do that?

atom/atom#10297
