### ISSUE TITLE
Can't update to 0.211.1 on Windows 10 due to node-gyp error

### ISSUE THREAD

**Issue by manuelbieh** [atom/tree-view#968]
Tried to update to 0.211.1 on Windows 10 and I get a node-gyp error. Now I dont know if it has something to do with the update to Node 6.9 that I did this week but since Atom comes bundled with Node 4.x as far as I know it should be independent from that.

Updating to 0.210.0 worked fine. Already re-installed Atom but the recent Atom version still has 0.210.0 included.

```
Updating to “tree-view@0.211.1” failed.Hide output…
The tree-view package is bundled with Atom and should not be explicitly installed.
You can run `apm uninstall tree-view` to uninstall it and then the version bundled
with Atom will be used.


> runas@3.1.1 install C:\Users\Manuel\AppData\Local\Temp\apm-install-dir-116931-1816-1ym2so6\node_modules\tree-view\node_modules\runas
> node-gyp rebuild


C:\Users\Manuel\AppData\Local\Temp\apm-install-dir-116931-1816-1ym2so6\node_modules\tree-view\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\Manuel\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Manuel\AppData\Local\atom\app-1.11.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
C:\Users\Manuel\AppData\Local\Temp\apm-install-dir-116931-1816-1ym2so6\node_modules\tree-view\node_modules\runas\build\runas.vcxproj(20,3): error MSB4019: Das importierte Projekt "C:\Microsoft.Cpp.Default.props" wurde nicht gefunden. Vergewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datentr�ger vorhanden ist.
C:\Users\Manuel\AppData\Local\Temp\apm-install-dir-116931-1816-1ym2so6
`-- (empty)


npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Manuel\AppData\Local\atom\app-1.11.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Manuel\\AppData\\Local\\atom\\app-1.11.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Manuel\\AppData\\Local\\atom\\app-1.11.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Manuel\AppData\Local\Temp\apm-install-dir-116931-1816-1ym2so6\node_modules\tree-view\node_modules\runas
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Manuel\AppData\Local\Temp\apm-install-dir-116931-1816-1ym2so6\package.json'
npm WARN apm-install-dir-116931-1816-1ym2so6 No description
npm WARN apm-install-dir-116931-1816-1ym2so6 No repository field.
npm WARN apm-install-dir-116931-1816-1ym2so6 No README data
npm WARN apm-install-dir-116931-1816-1ym2so6 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Manuel\\AppData\\Local\\atom\\app-1.11.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Manuel\\AppData\\Local\\atom\\app-1.11.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Manuel\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Manuel\\.atom\\.apmrc" "install" "C:\\Users\\Manuel\\AppData\\Local\\Temp\\d-116931-1816-yykg7h\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style" "--msvs_version=2013"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Manuel\AppData\Local\Temp\apm-install-dir-116931-1816-1ym2so6\npm-debug.log
npm ERR! code 1
```

**Comment by Ben3eeE** [comment]
Thanks for the report!

As you can see in the log:
```
Updating to “tree-view@0.211.1” failed.Hide output…
The tree-view package is bundled with Atom and should not be explicitly installed.
You can run `apm uninstall tree-view` to uninstall it and then the version bundled
with Atom will be used.
```

You are not supposed to manually install bundled packages. That can lead to many problems because the packages may have breaking changes. Please uninstall the tree-view package that you have manually installed and use the version that is bundled with Atom. The upgrade will come when a new version is released with Atom.

**Comment by manuelbieh** [comment]
I did not! I used the Atom updater to update. Never tried to update the package manually?!

![http://i.imgur.com/Q7BXaeW.png](http://i.imgur.com/Q7BXaeW.png)

![http://i.imgur.com/ZsZ38Fq.png](http://i.imgur.com/ZsZ38Fq.png)

![http://i.imgur.com/ZFJtglG.png](http://i.imgur.com/ZFJtglG.png)

**Comment by Ben3eeE** [comment]
You will get update notifications for packages if you at any time have manually installed it. There are also community packages that automatically update packages which include bundled packages which would cause you to get update notifications for them.

**Comment by 50Wliu** [comment]
Uninstall auto-update-packages if you have it installed, and also please paste the output of  `apm list --installed` here

**Comment by manuelbieh** [comment]
I dont have auto-update-packages installed.

```
$ apm list --installed
Community Packages (44) C:\Users\Manuel\.atom\packages
├── activate-power-mode@1.1.0
├── atom-beautify@0.29.13
├── atom-csscomb@2.0.4
├── atom-handlebars@1.3.0
├── atom-react-es2015@1.0.2
├── atom-wrap-in-tag@0.6.0
├── autoclose-html@0.23.0
├── autocomplete-json@5.1.0
├── autocomplete-modules@1.6.7
├── case-switch@2.2.4
├── clipboard-plus@0.5.1
├── css-snippets@1.1.0
├── editorconfig@1.7.2
├── file-types@0.5.4-p1
├── font-viewer@0.3.1
├── fonts@1.7.0
├── git-blame@0.4.11
├── git-plus@5.18.0
├── github-2016-syntax@1.2.0
├── highlight-selected@0.11.2
├── hyperclick@0.0.39
├── hyperclick-php@0.2.1
├── incremental-search@5.1.0
├── js-hyperclick@1.9.0
├── keyboard-localization@1.4.18
├── language-babel@2.45.0
├── linter@1.11.18
├── linter-eslint@8.0.0
├── logo-file-icons@1.2.0
├── monokai@0.18.0
├── nuclide
├── open-recent@5.0.0
├── package-sync@1.1.0
├── pdf-view@0.50.0
├── php-twig@4.0.0
├── pigments@0.37.0
├── project-manager@3.3.2
├── react@0.16.1
├── react-es6-snippets@0.3.0
├── Sublime-Style-Column-Selection@1.7.2
├── svg-preview@0.10.0
├── sync-settings@0.7.2
├── tabs-to-spaces@1.0.2
└── tree-view@0.210.0

└── (empty)
```

**Comment by 50Wliu** [comment]
Run `apm uninstall tree-view` and you should be set.

**Comment by manuelbieh** [comment]
Worked, thank you! 

Can't remember having tree-view (or any other core package) installed manually though?! ...

**Comment by 50Wliu** [comment]
We all forget things sometimes :wink:.
Though it may also have something to do with nuclide - I know that it disables tree-view when you install it.

As long as it's fixed though, that's good!
