### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, realpath '/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar'

### ISSUE THREAD

**Issue by tonydeng** [atom/tree-view#981]
```javascript
Error: ENOENT: no such file or directory, realpath '/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar'
    at Error (native)
    at realpathSync (fs.js:1584:18)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:326:24)
    at Function.Module._findPath (module.js:167:25)
    at Module._resolveFilename (module.js:438:25)
    at Module._resolveFilename (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:53:23)
    at atom-text-editor.TextEditorElement.initializeContent (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:57:79)
    at atom-text-editor.TextEditorElement.setModel (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:138:12)
    at atom-text-editor.TextEditorElement.buildModel (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:178:19)
    at atom-text-editor.TextEditorElement.getModel (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:174:56)
    at new TextEditorView (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/text-editor-view.js:40:34)
    at Object.content (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/dialog.js:28:39)
    at Builder.tag (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.module.exports.Dialog.content (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/dialog.js:20:19)
    at Function.<anonymous> (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:123:10)
    at AddDialog.View [as constructor] (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:155:33)
    at AddDialog.Dialog [as constructor] (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/dialog.js:14:43)
    at new AddDialog (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/add-dialog.js:30:39)
    at TreeView.module.exports.TreeView.add (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:1138:16)
    at atom-workspace.disposables.add.atom.commands.add.tree-view:add-file (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/main.js:52:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1132:28)
    at EventEmitter.outerCallback (/Users/tonydeng/Library/Application Support/com.github.atom.ShipIt/update.GOxUuqf/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:332:25)
    at emitThree (events.js:116:13)
```

**Comment by AndreaGriffiths11** [comment]
Thanks for reaching out!

Unfortunately there is not enough information here to be actionable. We are going to have to close this, if you have more information please open a new issue and fill out the new issue template.
